"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.renderNostrCard = renderNostrCard;
var lit_1 = require("lit");
var format_1 = require("../format");
var channels_config_1 = require("./channels.config");
var channels_nostr_profile_form_1 = require("./channels.nostr-profile-form");
/**
 * Truncate a pubkey for display (shows first and last 8 chars)
 */
function truncatePubkey(pubkey) {
    if (!pubkey) {
        return "n/a";
    }
    if (pubkey.length <= 20) {
        return pubkey;
    }
    return "".concat(pubkey.slice(0, 8), "...").concat(pubkey.slice(-8));
}
function renderNostrCard(params) {
    var _a, _b, _c, _d, _e, _f, _g, _h, _j;
    var props = params.props, nostr = params.nostr, nostrAccounts = params.nostrAccounts, accountCountLabel = params.accountCountLabel, profileFormState = params.profileFormState, profileFormCallbacks = params.profileFormCallbacks, onEditProfile = params.onEditProfile;
    var primaryAccount = nostrAccounts[0];
    var summaryConfigured = (_b = (_a = nostr === null || nostr === void 0 ? void 0 : nostr.configured) !== null && _a !== void 0 ? _a : primaryAccount === null || primaryAccount === void 0 ? void 0 : primaryAccount.configured) !== null && _b !== void 0 ? _b : false;
    var summaryRunning = (_d = (_c = nostr === null || nostr === void 0 ? void 0 : nostr.running) !== null && _c !== void 0 ? _c : primaryAccount === null || primaryAccount === void 0 ? void 0 : primaryAccount.running) !== null && _d !== void 0 ? _d : false;
    var summaryPublicKey = (_e = nostr === null || nostr === void 0 ? void 0 : nostr.publicKey) !== null && _e !== void 0 ? _e : primaryAccount === null || primaryAccount === void 0 ? void 0 : primaryAccount.publicKey;
    var summaryLastStartAt = (_g = (_f = nostr === null || nostr === void 0 ? void 0 : nostr.lastStartAt) !== null && _f !== void 0 ? _f : primaryAccount === null || primaryAccount === void 0 ? void 0 : primaryAccount.lastStartAt) !== null && _g !== void 0 ? _g : null;
    var summaryLastError = (_j = (_h = nostr === null || nostr === void 0 ? void 0 : nostr.lastError) !== null && _h !== void 0 ? _h : primaryAccount === null || primaryAccount === void 0 ? void 0 : primaryAccount.lastError) !== null && _j !== void 0 ? _j : null;
    var hasMultipleAccounts = nostrAccounts.length > 1;
    var showingForm = profileFormState !== null && profileFormState !== undefined;
    var renderAccountCard = function (account) {
        var _a, _b, _c;
        var publicKey = account.publicKey;
        var profile = account.profile;
        var displayName = (_c = (_b = (_a = profile === null || profile === void 0 ? void 0 : profile.displayName) !== null && _a !== void 0 ? _a : profile === null || profile === void 0 ? void 0 : profile.name) !== null && _b !== void 0 ? _b : account.name) !== null && _c !== void 0 ? _c : account.accountId;
        return (0, lit_1.html)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["\n      <div class=\"account-card\">\n        <div class=\"account-card-header\">\n          <div class=\"account-card-title\">", "</div>\n          <div class=\"account-card-id\">", "</div>\n        </div>\n        <div class=\"status-list account-card-status\">\n          <div>\n            <span class=\"label\">Running</span>\n            <span>", "</span>\n          </div>\n          <div>\n            <span class=\"label\">Configured</span>\n            <span>", "</span>\n          </div>\n          <div>\n            <span class=\"label\">Public Key</span>\n            <span class=\"monospace\" title=\"", "\">", "</span>\n          </div>\n          <div>\n            <span class=\"label\">Last inbound</span>\n            <span>", "</span>\n          </div>\n          ", "\n        </div>\n      </div>\n    "], ["\n      <div class=\"account-card\">\n        <div class=\"account-card-header\">\n          <div class=\"account-card-title\">", "</div>\n          <div class=\"account-card-id\">", "</div>\n        </div>\n        <div class=\"status-list account-card-status\">\n          <div>\n            <span class=\"label\">Running</span>\n            <span>", "</span>\n          </div>\n          <div>\n            <span class=\"label\">Configured</span>\n            <span>", "</span>\n          </div>\n          <div>\n            <span class=\"label\">Public Key</span>\n            <span class=\"monospace\" title=\"", "\">", "</span>\n          </div>\n          <div>\n            <span class=\"label\">Last inbound</span>\n            <span>", "</span>\n          </div>\n          ", "\n        </div>\n      </div>\n    "])), displayName, account.accountId, account.running ? "Yes" : "No", account.configured ? "Yes" : "No", publicKey !== null && publicKey !== void 0 ? publicKey : "", truncatePubkey(publicKey), account.lastInboundAt ? (0, format_1.formatAgo)(account.lastInboundAt) : "n/a", account.lastError
            ? (0, lit_1.html)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["\n                <div class=\"account-card-error\">", "</div>\n              "], ["\n                <div class=\"account-card-error\">", "</div>\n              "])), account.lastError) : lit_1.nothing);
    };
    var renderProfileSection = function () {
        var _a, _b, _c;
        // If showing form, render the form instead of the read-only view
        if (showingForm && profileFormCallbacks) {
            return (0, channels_nostr_profile_form_1.renderNostrProfileForm)({
                state: profileFormState,
                callbacks: profileFormCallbacks,
                accountId: (_b = (_a = nostrAccounts[0]) === null || _a === void 0 ? void 0 : _a.accountId) !== null && _b !== void 0 ? _b : "default",
            });
        }
        var profile = (_c = primaryAccount === null || primaryAccount === void 0 ? void 0 : primaryAccount.profile) !== null && _c !== void 0 ? _c : nostr === null || nostr === void 0 ? void 0 : nostr.profile;
        var _d = profile !== null && profile !== void 0 ? profile : {}, name = _d.name, displayName = _d.displayName, about = _d.about, picture = _d.picture, nip05 = _d.nip05;
        var hasAnyProfileData = name || displayName || about || picture || nip05;
        return (0, lit_1.html)(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n      <div style=\"margin-top: 16px; padding: 12px; background: var(--bg-secondary); border-radius: 8px;\">\n        <div style=\"display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;\">\n          <div style=\"font-weight: 500;\">Profile</div>\n          ", "\n        </div>\n        ", "\n      </div>\n    "], ["\n      <div style=\"margin-top: 16px; padding: 12px; background: var(--bg-secondary); border-radius: 8px;\">\n        <div style=\"display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px;\">\n          <div style=\"font-weight: 500;\">Profile</div>\n          ", "\n        </div>\n        ", "\n      </div>\n    "])), summaryConfigured
            ? (0, lit_1.html)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n                <button\n                  class=\"btn btn-sm\"\n                  @click=", "\n                  style=\"font-size: 12px; padding: 4px 8px;\"\n                >\n                  Edit Profile\n                </button>\n              "], ["\n                <button\n                  class=\"btn btn-sm\"\n                  @click=", "\n                  style=\"font-size: 12px; padding: 4px 8px;\"\n                >\n                  Edit Profile\n                </button>\n              "])), onEditProfile) : lit_1.nothing, hasAnyProfileData
            ? (0, lit_1.html)(templateObject_9 || (templateObject_9 = __makeTemplateObject(["\n              <div class=\"status-list\">\n                ", "\n                ", "\n                ", "\n                ", "\n                ", "\n              </div>\n            "], ["\n              <div class=\"status-list\">\n                ", "\n                ", "\n                ", "\n                ", "\n                ", "\n              </div>\n            "])), picture
                ? (0, lit_1.html)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n                      <div style=\"margin-bottom: 8px;\">\n                        <img\n                          src=", "\n                          alt=\"Profile picture\"\n                          style=\"width: 48px; height: 48px; border-radius: 50%; object-fit: cover; border: 2px solid var(--border-color);\"\n                          @error=", "\n                        />\n                      </div>\n                    "], ["\n                      <div style=\"margin-bottom: 8px;\">\n                        <img\n                          src=", "\n                          alt=\"Profile picture\"\n                          style=\"width: 48px; height: 48px; border-radius: 50%; object-fit: cover; border: 2px solid var(--border-color);\"\n                          @error=", "\n                        />\n                      </div>\n                    "])), picture, function (e) {
                    e.target.style.display = "none";
                }) : lit_1.nothing, name ? (0, lit_1.html)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["<div><span class=\"label\">Name</span><span>", "</span></div>"], ["<div><span class=\"label\">Name</span><span>", "</span></div>"])), name) : lit_1.nothing, displayName
                ? (0, lit_1.html)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["<div><span class=\"label\">Display Name</span><span>", "</span></div>"], ["<div><span class=\"label\">Display Name</span><span>", "</span></div>"])), displayName) : lit_1.nothing, about
                ? (0, lit_1.html)(templateObject_7 || (templateObject_7 = __makeTemplateObject(["<div><span class=\"label\">About</span><span style=\"max-width: 300px; overflow: hidden; text-overflow: ellipsis;\">", "</span></div>"], ["<div><span class=\"label\">About</span><span style=\"max-width: 300px; overflow: hidden; text-overflow: ellipsis;\">", "</span></div>"])), about) : lit_1.nothing, nip05 ? (0, lit_1.html)(templateObject_8 || (templateObject_8 = __makeTemplateObject(["<div><span class=\"label\">NIP-05</span><span>", "</span></div>"], ["<div><span class=\"label\">NIP-05</span><span>", "</span></div>"])), nip05) : lit_1.nothing) : (0, lit_1.html)(templateObject_10 || (templateObject_10 = __makeTemplateObject(["\n                <div style=\"color: var(--text-muted); font-size: 13px\">\n                  No profile set. Click \"Edit Profile\" to add your name, bio, and avatar.\n                </div>\n              "], ["\n                <div style=\"color: var(--text-muted); font-size: 13px\">\n                  No profile set. Click \"Edit Profile\" to add your name, bio, and avatar.\n                </div>\n              "]))));
    };
    return (0, lit_1.html)(templateObject_15 || (templateObject_15 = __makeTemplateObject(["\n    <div class=\"card\">\n      <div class=\"card-title\">Nostr</div>\n      <div class=\"card-sub\">Decentralized DMs via Nostr relays (NIP-04).</div>\n      ", "\n\n      ", "\n\n      ", "\n\n      ", "\n\n      ", "\n\n      <div class=\"row\" style=\"margin-top: 12px;\">\n        <button class=\"btn\" @click=", ">Refresh</button>\n      </div>\n    </div>\n  "], ["\n    <div class=\"card\">\n      <div class=\"card-title\">Nostr</div>\n      <div class=\"card-sub\">Decentralized DMs via Nostr relays (NIP-04).</div>\n      ", "\n\n      ", "\n\n      ", "\n\n      ", "\n\n      ", "\n\n      <div class=\"row\" style=\"margin-top: 12px;\">\n        <button class=\"btn\" @click=", ">Refresh</button>\n      </div>\n    </div>\n  "])), accountCountLabel, hasMultipleAccounts
        ? (0, lit_1.html)(templateObject_12 || (templateObject_12 = __makeTemplateObject(["\n            <div class=\"account-card-list\">\n              ", "\n            </div>\n          "], ["\n            <div class=\"account-card-list\">\n              ", "\n            </div>\n          "])), nostrAccounts.map(function (account) { return renderAccountCard(account); })) : (0, lit_1.html)(templateObject_13 || (templateObject_13 = __makeTemplateObject(["\n            <div class=\"status-list\" style=\"margin-top: 16px;\">\n              <div>\n                <span class=\"label\">Configured</span>\n                <span>", "</span>\n              </div>\n              <div>\n                <span class=\"label\">Running</span>\n                <span>", "</span>\n              </div>\n              <div>\n                <span class=\"label\">Public Key</span>\n                <span class=\"monospace\" title=\"", "\"\n                  >", "</span\n                >\n              </div>\n              <div>\n                <span class=\"label\">Last start</span>\n                <span>", "</span>\n              </div>\n            </div>\n          "], ["\n            <div class=\"status-list\" style=\"margin-top: 16px;\">\n              <div>\n                <span class=\"label\">Configured</span>\n                <span>", "</span>\n              </div>\n              <div>\n                <span class=\"label\">Running</span>\n                <span>", "</span>\n              </div>\n              <div>\n                <span class=\"label\">Public Key</span>\n                <span class=\"monospace\" title=\"", "\"\n                  >", "</span\n                >\n              </div>\n              <div>\n                <span class=\"label\">Last start</span>\n                <span>", "</span>\n              </div>\n            </div>\n          "])), summaryConfigured ? "Yes" : "No", summaryRunning ? "Yes" : "No", summaryPublicKey !== null && summaryPublicKey !== void 0 ? summaryPublicKey : "", truncatePubkey(summaryPublicKey), summaryLastStartAt ? (0, format_1.formatAgo)(summaryLastStartAt) : "n/a"), summaryLastError
        ? (0, lit_1.html)(templateObject_14 || (templateObject_14 = __makeTemplateObject(["<div class=\"callout danger\" style=\"margin-top: 12px;\">", "</div>"], ["<div class=\"callout danger\" style=\"margin-top: 12px;\">", "</div>"])), summaryLastError) : lit_1.nothing, renderProfileSection(), (0, channels_config_1.renderChannelConfigSection)({ channelId: "nostr", props: props }), function () { return props.onRefresh(false); });
}
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11, templateObject_12, templateObject_13, templateObject_14, templateObject_15;
