"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.renderSlackCard = renderSlackCard;
var lit_1 = require("lit");
var format_1 = require("../format");
var channels_config_1 = require("./channels.config");
function renderSlackCard(params) {
    var _a, _b;
    var props = params.props, slack = params.slack, accountCountLabel = params.accountCountLabel;
    return (0, lit_1.html)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    <div class=\"card\">\n      <div class=\"card-title\">Slack</div>\n      <div class=\"card-sub\">Socket mode status and channel configuration.</div>\n      ", "\n\n      <div class=\"status-list\" style=\"margin-top: 16px;\">\n        <div>\n          <span class=\"label\">Configured</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Running</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Last start</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Last probe</span>\n          <span>", "</span>\n        </div>\n      </div>\n\n      ", "\n\n      ", "\n\n      ", "\n\n      <div class=\"row\" style=\"margin-top: 12px;\">\n        <button class=\"btn\" @click=", ">\n          Probe\n        </button>\n      </div>\n    </div>\n  "], ["\n    <div class=\"card\">\n      <div class=\"card-title\">Slack</div>\n      <div class=\"card-sub\">Socket mode status and channel configuration.</div>\n      ", "\n\n      <div class=\"status-list\" style=\"margin-top: 16px;\">\n        <div>\n          <span class=\"label\">Configured</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Running</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Last start</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Last probe</span>\n          <span>", "</span>\n        </div>\n      </div>\n\n      ", "\n\n      ", "\n\n      ", "\n\n      <div class=\"row\" style=\"margin-top: 12px;\">\n        <button class=\"btn\" @click=", ">\n          Probe\n        </button>\n      </div>\n    </div>\n  "])), accountCountLabel, (slack === null || slack === void 0 ? void 0 : slack.configured) ? "Yes" : "No", (slack === null || slack === void 0 ? void 0 : slack.running) ? "Yes" : "No", (slack === null || slack === void 0 ? void 0 : slack.lastStartAt) ? (0, format_1.formatAgo)(slack.lastStartAt) : "n/a", (slack === null || slack === void 0 ? void 0 : slack.lastProbeAt) ? (0, format_1.formatAgo)(slack.lastProbeAt) : "n/a", (slack === null || slack === void 0 ? void 0 : slack.lastError)
        ? (0, lit_1.html)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["<div class=\"callout danger\" style=\"margin-top: 12px;\">\n            ", "\n          </div>"], ["<div class=\"callout danger\" style=\"margin-top: 12px;\">\n            ", "\n          </div>"])), slack.lastError) : lit_1.nothing, (slack === null || slack === void 0 ? void 0 : slack.probe)
        ? (0, lit_1.html)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["<div class=\"callout\" style=\"margin-top: 12px;\">\n            Probe ", " \u00B7\n            ", " ", "\n          </div>"], ["<div class=\"callout\" style=\"margin-top: 12px;\">\n            Probe ", " \u00B7\n            ", " ", "\n          </div>"])), slack.probe.ok ? "ok" : "failed", (_a = slack.probe.status) !== null && _a !== void 0 ? _a : "", (_b = slack.probe.error) !== null && _b !== void 0 ? _b : "") : lit_1.nothing, (0, channels_config_1.renderChannelConfigSection)({ channelId: "slack", props: props }), function () { return props.onRefresh(true); });
}
var templateObject_1, templateObject_2, templateObject_3;
