"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.renderSignalCard = renderSignalCard;
var lit_1 = require("lit");
var format_1 = require("../format");
var channels_config_1 = require("./channels.config");
function renderSignalCard(params) {
    var _a, _b, _c;
    var props = params.props, signal = params.signal, accountCountLabel = params.accountCountLabel;
    return (0, lit_1.html)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n    <div class=\"card\">\n      <div class=\"card-title\">Signal</div>\n      <div class=\"card-sub\">signal-cli status and channel configuration.</div>\n      ", "\n\n      <div class=\"status-list\" style=\"margin-top: 16px;\">\n        <div>\n          <span class=\"label\">Configured</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Running</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Base URL</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Last start</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Last probe</span>\n          <span>", "</span>\n        </div>\n      </div>\n\n      ", "\n\n      ", "\n\n      ", "\n\n      <div class=\"row\" style=\"margin-top: 12px;\">\n        <button class=\"btn\" @click=", ">\n          Probe\n        </button>\n      </div>\n    </div>\n  "], ["\n    <div class=\"card\">\n      <div class=\"card-title\">Signal</div>\n      <div class=\"card-sub\">signal-cli status and channel configuration.</div>\n      ", "\n\n      <div class=\"status-list\" style=\"margin-top: 16px;\">\n        <div>\n          <span class=\"label\">Configured</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Running</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Base URL</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Last start</span>\n          <span>", "</span>\n        </div>\n        <div>\n          <span class=\"label\">Last probe</span>\n          <span>", "</span>\n        </div>\n      </div>\n\n      ", "\n\n      ", "\n\n      ", "\n\n      <div class=\"row\" style=\"margin-top: 12px;\">\n        <button class=\"btn\" @click=", ">\n          Probe\n        </button>\n      </div>\n    </div>\n  "])), accountCountLabel, (signal === null || signal === void 0 ? void 0 : signal.configured) ? "Yes" : "No", (signal === null || signal === void 0 ? void 0 : signal.running) ? "Yes" : "No", (_a = signal === null || signal === void 0 ? void 0 : signal.baseUrl) !== null && _a !== void 0 ? _a : "n/a", (signal === null || signal === void 0 ? void 0 : signal.lastStartAt) ? (0, format_1.formatAgo)(signal.lastStartAt) : "n/a", (signal === null || signal === void 0 ? void 0 : signal.lastProbeAt) ? (0, format_1.formatAgo)(signal.lastProbeAt) : "n/a", (signal === null || signal === void 0 ? void 0 : signal.lastError)
        ? (0, lit_1.html)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["<div class=\"callout danger\" style=\"margin-top: 12px;\">\n            ", "\n          </div>"], ["<div class=\"callout danger\" style=\"margin-top: 12px;\">\n            ", "\n          </div>"])), signal.lastError) : lit_1.nothing, (signal === null || signal === void 0 ? void 0 : signal.probe)
        ? (0, lit_1.html)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["<div class=\"callout\" style=\"margin-top: 12px;\">\n            Probe ", " \u00B7\n            ", " ", "\n          </div>"], ["<div class=\"callout\" style=\"margin-top: 12px;\">\n            Probe ", " \u00B7\n            ", " ", "\n          </div>"])), signal.probe.ok ? "ok" : "failed", (_b = signal.probe.status) !== null && _b !== void 0 ? _b : "", (_c = signal.probe.error) !== null && _c !== void 0 ? _c : "") : lit_1.nothing, (0, channels_config_1.renderChannelConfigSection)({ channelId: "signal", props: props }), function () { return props.onRefresh(true); });
}
var templateObject_1, templateObject_2, templateObject_3;
