"use strict";
var __makeTemplateObject = (this && this.__makeTemplateObject) || function (cooked, raw) {
    if (Object.defineProperty) { Object.defineProperty(cooked, "raw", { value: raw }); } else { cooked.raw = raw; }
    return cooked;
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.renderInstances = renderInstances;
var lit_1 = require("lit");
var presenter_1 = require("../presenter");
function renderInstances(props) {
    return (0, lit_1.html)(templateObject_4 || (templateObject_4 = __makeTemplateObject(["\n    <section class=\"card\">\n      <div class=\"row\" style=\"justify-content: space-between;\">\n        <div>\n          <div class=\"card-title\">Connected Instances</div>\n          <div class=\"card-sub\">Presence beacons from the gateway and clients.</div>\n        </div>\n        <button class=\"btn\" ?disabled=", " @click=", ">\n          ", "\n        </button>\n      </div>\n      ", "\n      ", "\n      <div class=\"list\" style=\"margin-top: 16px;\">\n        ", "\n      </div>\n    </section>\n  "], ["\n    <section class=\"card\">\n      <div class=\"row\" style=\"justify-content: space-between;\">\n        <div>\n          <div class=\"card-title\">Connected Instances</div>\n          <div class=\"card-sub\">Presence beacons from the gateway and clients.</div>\n        </div>\n        <button class=\"btn\" ?disabled=", " @click=", ">\n          ", "\n        </button>\n      </div>\n      ", "\n      ", "\n      <div class=\"list\" style=\"margin-top: 16px;\">\n        ", "\n      </div>\n    </section>\n  "])), props.loading, props.onRefresh, props.loading ? "Loading…" : "Refresh", props.lastError
        ? (0, lit_1.html)(templateObject_1 || (templateObject_1 = __makeTemplateObject(["<div class=\"callout danger\" style=\"margin-top: 12px;\">\n            ", "\n          </div>"], ["<div class=\"callout danger\" style=\"margin-top: 12px;\">\n            ", "\n          </div>"])), props.lastError) : lit_1.nothing, props.statusMessage
        ? (0, lit_1.html)(templateObject_2 || (templateObject_2 = __makeTemplateObject(["<div class=\"callout\" style=\"margin-top: 12px;\">\n            ", "\n          </div>"], ["<div class=\"callout\" style=\"margin-top: 12px;\">\n            ", "\n          </div>"])), props.statusMessage) : lit_1.nothing, props.entries.length === 0
        ? (0, lit_1.html)(templateObject_3 || (templateObject_3 = __makeTemplateObject(["\n                <div class=\"muted\">No instances reported yet.</div>\n              "], ["\n                <div class=\"muted\">No instances reported yet.</div>\n              "]))) : props.entries.map(function (entry) { return renderEntry(entry); }));
}
function renderEntry(entry) {
    var _a, _b, _c;
    var lastInput = entry.lastInputSeconds != null ? "".concat(entry.lastInputSeconds, "s ago") : "n/a";
    var mode = (_a = entry.mode) !== null && _a !== void 0 ? _a : "unknown";
    var roles = Array.isArray(entry.roles) ? entry.roles.filter(Boolean) : [];
    var scopes = Array.isArray(entry.scopes) ? entry.scopes.filter(Boolean) : [];
    var scopesLabel = scopes.length > 0
        ? scopes.length > 3
            ? "".concat(scopes.length, " scopes")
            : "scopes: ".concat(scopes.join(", "))
        : null;
    return (0, lit_1.html)(templateObject_11 || (templateObject_11 = __makeTemplateObject(["\n    <div class=\"list-item\">\n      <div class=\"list-main\">\n        <div class=\"list-title\">", "</div>\n        <div class=\"list-sub\">", "</div>\n        <div class=\"chip-row\">\n          <span class=\"chip\">", "</span>\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n        </div>\n      </div>\n      <div class=\"list-meta\">\n        <div>", "</div>\n        <div class=\"muted\">Last input ", "</div>\n        <div class=\"muted\">Reason ", "</div>\n      </div>\n    </div>\n  "], ["\n    <div class=\"list-item\">\n      <div class=\"list-main\">\n        <div class=\"list-title\">", "</div>\n        <div class=\"list-sub\">", "</div>\n        <div class=\"chip-row\">\n          <span class=\"chip\">", "</span>\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n          ", "\n        </div>\n      </div>\n      <div class=\"list-meta\">\n        <div>", "</div>\n        <div class=\"muted\">Last input ", "</div>\n        <div class=\"muted\">Reason ", "</div>\n      </div>\n    </div>\n  "])), (_b = entry.host) !== null && _b !== void 0 ? _b : "unknown host", (0, presenter_1.formatPresenceSummary)(entry), mode, roles.map(function (role) { return (0, lit_1.html)(templateObject_5 || (templateObject_5 = __makeTemplateObject(["<span class=\"chip\">", "</span>"], ["<span class=\"chip\">", "</span>"])), role); }), scopesLabel ? (0, lit_1.html)(templateObject_6 || (templateObject_6 = __makeTemplateObject(["<span class=\"chip\">", "</span>"], ["<span class=\"chip\">", "</span>"])), scopesLabel) : lit_1.nothing, entry.platform ? (0, lit_1.html)(templateObject_7 || (templateObject_7 = __makeTemplateObject(["<span class=\"chip\">", "</span>"], ["<span class=\"chip\">", "</span>"])), entry.platform) : lit_1.nothing, entry.deviceFamily ? (0, lit_1.html)(templateObject_8 || (templateObject_8 = __makeTemplateObject(["<span class=\"chip\">", "</span>"], ["<span class=\"chip\">", "</span>"])), entry.deviceFamily) : lit_1.nothing, entry.modelIdentifier
        ? (0, lit_1.html)(templateObject_9 || (templateObject_9 = __makeTemplateObject(["<span class=\"chip\">", "</span>"], ["<span class=\"chip\">", "</span>"])), entry.modelIdentifier) : lit_1.nothing, entry.version ? (0, lit_1.html)(templateObject_10 || (templateObject_10 = __makeTemplateObject(["<span class=\"chip\">", "</span>"], ["<span class=\"chip\">", "</span>"])), entry.version) : lit_1.nothing, (0, presenter_1.formatPresenceAge)(entry), lastInput, (_c = entry.reason) !== null && _c !== void 0 ? _c : "");
}
var templateObject_1, templateObject_2, templateObject_3, templateObject_4, templateObject_5, templateObject_6, templateObject_7, templateObject_8, templateObject_9, templateObject_10, templateObject_11;
