"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.runDaemonStatus = exports.runDaemonUninstall = exports.runDaemonStop = exports.runDaemonStart = exports.runDaemonRestart = exports.runDaemonInstall = void 0;
var install_js_1 = require("./install.js");
Object.defineProperty(exports, "runDaemonInstall", { enumerable: true, get: function () { return install_js_1.runDaemonInstall; } });
var lifecycle_js_1 = require("./lifecycle.js");
Object.defineProperty(exports, "runDaemonRestart", { enumerable: true, get: function () { return lifecycle_js_1.runDaemonRestart; } });
Object.defineProperty(exports, "runDaemonStart", { enumerable: true, get: function () { return lifecycle_js_1.runDaemonStart; } });
Object.defineProperty(exports, "runDaemonStop", { enumerable: true, get: function () { return lifecycle_js_1.runDaemonStop; } });
Object.defineProperty(exports, "runDaemonUninstall", { enumerable: true, get: function () { return lifecycle_js_1.runDaemonUninstall; } });
var status_js_1 = require("./status.js");
Object.defineProperty(exports, "runDaemonStatus", { enumerable: true, get: function () { return status_js_1.runDaemonStatus; } });
