"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.runDaemonUninstall = exports.runDaemonStop = exports.runDaemonStatus = exports.runDaemonStart = exports.runDaemonRestart = exports.runDaemonInstall = exports.registerDaemonCli = void 0;
var register_js_1 = require("./daemon-cli/register.js");
Object.defineProperty(exports, "registerDaemonCli", { enumerable: true, get: function () { return register_js_1.registerDaemonCli; } });
var runners_js_1 = require("./daemon-cli/runners.js");
Object.defineProperty(exports, "runDaemonInstall", { enumerable: true, get: function () { return runners_js_1.runDaemonInstall; } });
Object.defineProperty(exports, "runDaemonRestart", { enumerable: true, get: function () { return runners_js_1.runDaemonRestart; } });
Object.defineProperty(exports, "runDaemonStart", { enumerable: true, get: function () { return runners_js_1.runDaemonStart; } });
Object.defineProperty(exports, "runDaemonStatus", { enumerable: true, get: function () { return runners_js_1.runDaemonStatus; } });
Object.defineProperty(exports, "runDaemonStop", { enumerable: true, get: function () { return runners_js_1.runDaemonStop; } });
Object.defineProperty(exports, "runDaemonUninstall", { enumerable: true, get: function () { return runners_js_1.runDaemonUninstall; } });
