"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.startTelegramWebhook = exports.sendMessageTelegram = exports.reactMessageTelegram = exports.monitorTelegramProvider = exports.createTelegramWebhookCallback = exports.createTelegramBot = void 0;
var bot_js_1 = require("./bot.js");
Object.defineProperty(exports, "createTelegramBot", { enumerable: true, get: function () { return bot_js_1.createTelegramBot; } });
Object.defineProperty(exports, "createTelegramWebhookCallback", { enumerable: true, get: function () { return bot_js_1.createTelegramWebhookCallback; } });
var monitor_js_1 = require("./monitor.js");
Object.defineProperty(exports, "monitorTelegramProvider", { enumerable: true, get: function () { return monitor_js_1.monitorTelegramProvider; } });
var send_js_1 = require("./send.js");
Object.defineProperty(exports, "reactMessageTelegram", { enumerable: true, get: function () { return send_js_1.reactMessageTelegram; } });
Object.defineProperty(exports, "sendMessageTelegram", { enumerable: true, get: function () { return send_js_1.sendMessageTelegram; } });
var webhook_js_1 = require("./webhook.js");
Object.defineProperty(exports, "startTelegramWebhook", { enumerable: true, get: function () { return webhook_js_1.startTelegramWebhook; } });
