"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.modelsSetImageCommand = exports.modelsSetCommand = exports.modelsScanCommand = exports.modelsStatusCommand = exports.modelsListCommand = exports.modelsImageFallbacksRemoveCommand = exports.modelsImageFallbacksListCommand = exports.modelsImageFallbacksClearCommand = exports.modelsImageFallbacksAddCommand = exports.modelsFallbacksRemoveCommand = exports.modelsFallbacksListCommand = exports.modelsFallbacksClearCommand = exports.modelsFallbacksAddCommand = exports.modelsAuthOrderSetCommand = exports.modelsAuthOrderGetCommand = exports.modelsAuthOrderClearCommand = exports.modelsAuthSetupTokenCommand = exports.modelsAuthPasteTokenCommand = exports.modelsAuthLoginCommand = exports.modelsAuthAddCommand = exports.modelsAliasesRemoveCommand = exports.modelsAliasesListCommand = exports.modelsAliasesAddCommand = exports.githubCopilotLoginCommand = void 0;
var github_copilot_auth_js_1 = require("../providers/github-copilot-auth.js");
Object.defineProperty(exports, "githubCopilotLoginCommand", { enumerable: true, get: function () { return github_copilot_auth_js_1.githubCopilotLoginCommand; } });
var aliases_js_1 = require("./models/aliases.js");
Object.defineProperty(exports, "modelsAliasesAddCommand", { enumerable: true, get: function () { return aliases_js_1.modelsAliasesAddCommand; } });
Object.defineProperty(exports, "modelsAliasesListCommand", { enumerable: true, get: function () { return aliases_js_1.modelsAliasesListCommand; } });
Object.defineProperty(exports, "modelsAliasesRemoveCommand", { enumerable: true, get: function () { return aliases_js_1.modelsAliasesRemoveCommand; } });
var auth_js_1 = require("./models/auth.js");
Object.defineProperty(exports, "modelsAuthAddCommand", { enumerable: true, get: function () { return auth_js_1.modelsAuthAddCommand; } });
Object.defineProperty(exports, "modelsAuthLoginCommand", { enumerable: true, get: function () { return auth_js_1.modelsAuthLoginCommand; } });
Object.defineProperty(exports, "modelsAuthPasteTokenCommand", { enumerable: true, get: function () { return auth_js_1.modelsAuthPasteTokenCommand; } });
Object.defineProperty(exports, "modelsAuthSetupTokenCommand", { enumerable: true, get: function () { return auth_js_1.modelsAuthSetupTokenCommand; } });
var auth_order_js_1 = require("./models/auth-order.js");
Object.defineProperty(exports, "modelsAuthOrderClearCommand", { enumerable: true, get: function () { return auth_order_js_1.modelsAuthOrderClearCommand; } });
Object.defineProperty(exports, "modelsAuthOrderGetCommand", { enumerable: true, get: function () { return auth_order_js_1.modelsAuthOrderGetCommand; } });
Object.defineProperty(exports, "modelsAuthOrderSetCommand", { enumerable: true, get: function () { return auth_order_js_1.modelsAuthOrderSetCommand; } });
var fallbacks_js_1 = require("./models/fallbacks.js");
Object.defineProperty(exports, "modelsFallbacksAddCommand", { enumerable: true, get: function () { return fallbacks_js_1.modelsFallbacksAddCommand; } });
Object.defineProperty(exports, "modelsFallbacksClearCommand", { enumerable: true, get: function () { return fallbacks_js_1.modelsFallbacksClearCommand; } });
Object.defineProperty(exports, "modelsFallbacksListCommand", { enumerable: true, get: function () { return fallbacks_js_1.modelsFallbacksListCommand; } });
Object.defineProperty(exports, "modelsFallbacksRemoveCommand", { enumerable: true, get: function () { return fallbacks_js_1.modelsFallbacksRemoveCommand; } });
var image_fallbacks_js_1 = require("./models/image-fallbacks.js");
Object.defineProperty(exports, "modelsImageFallbacksAddCommand", { enumerable: true, get: function () { return image_fallbacks_js_1.modelsImageFallbacksAddCommand; } });
Object.defineProperty(exports, "modelsImageFallbacksClearCommand", { enumerable: true, get: function () { return image_fallbacks_js_1.modelsImageFallbacksClearCommand; } });
Object.defineProperty(exports, "modelsImageFallbacksListCommand", { enumerable: true, get: function () { return image_fallbacks_js_1.modelsImageFallbacksListCommand; } });
Object.defineProperty(exports, "modelsImageFallbacksRemoveCommand", { enumerable: true, get: function () { return image_fallbacks_js_1.modelsImageFallbacksRemoveCommand; } });
var list_js_1 = require("./models/list.js");
Object.defineProperty(exports, "modelsListCommand", { enumerable: true, get: function () { return list_js_1.modelsListCommand; } });
Object.defineProperty(exports, "modelsStatusCommand", { enumerable: true, get: function () { return list_js_1.modelsStatusCommand; } });
var scan_js_1 = require("./models/scan.js");
Object.defineProperty(exports, "modelsScanCommand", { enumerable: true, get: function () { return scan_js_1.modelsScanCommand; } });
var set_js_1 = require("./models/set.js");
Object.defineProperty(exports, "modelsSetCommand", { enumerable: true, get: function () { return set_js_1.modelsSetCommand; } });
var set_image_js_1 = require("./models/set-image.js");
Object.defineProperty(exports, "modelsSetImageCommand", { enumerable: true, get: function () { return set_image_js_1.modelsSetImageCommand; } });
