"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.KIMI_CODING_MODEL_ID = exports.DEFAULT_MINIMAX_BASE_URL = exports.buildMoonshotModelDefinition = exports.buildMinimaxModelDefinition = exports.buildMinimaxApiModelDefinition = exports.ZAI_DEFAULT_MODEL_REF = exports.XIAOMI_DEFAULT_MODEL_REF = exports.VERCEL_AI_GATEWAY_DEFAULT_MODEL_REF = exports.writeOAuthCredentials = exports.setZaiApiKey = exports.setXiaomiApiKey = exports.setVercelAiGatewayApiKey = exports.setVeniceApiKey = exports.setSyntheticApiKey = exports.setOpenrouterApiKey = exports.setOpencodeZenApiKey = exports.setMoonshotApiKey = exports.setMinimaxApiKey = exports.setKimiCodingApiKey = exports.setGeminiApiKey = exports.setAnthropicApiKey = exports.OPENROUTER_DEFAULT_MODEL_REF = exports.applyOpencodeZenProviderConfig = exports.applyOpencodeZenConfig = exports.applyMinimaxProviderConfig = exports.applyMinimaxHostedProviderConfig = exports.applyMinimaxHostedConfig = exports.applyMinimaxConfig = exports.applyMinimaxApiProviderConfig = exports.applyMinimaxApiConfig = exports.applyZaiConfig = exports.applyXiaomiProviderConfig = exports.applyXiaomiConfig = exports.applyVercelAiGatewayProviderConfig = exports.applyVercelAiGatewayConfig = exports.applyVeniceProviderConfig = exports.applyVeniceConfig = exports.applySyntheticProviderConfig = exports.applySyntheticConfig = exports.applyOpenrouterProviderConfig = exports.applyOpenrouterConfig = exports.applyMoonshotProviderConfig = exports.applyMoonshotConfig = exports.applyKimiCodeProviderConfig = exports.applyKimiCodeConfig = exports.applyAuthProfileConfig = exports.VENICE_DEFAULT_MODEL_REF = exports.VENICE_DEFAULT_MODEL_ID = exports.SYNTHETIC_DEFAULT_MODEL_REF = exports.SYNTHETIC_DEFAULT_MODEL_ID = void 0;
exports.MOONSHOT_DEFAULT_MODEL_REF = exports.MOONSHOT_DEFAULT_MODEL_ID = exports.MOONSHOT_BASE_URL = exports.MINIMAX_HOSTED_MODEL_REF = exports.MINIMAX_HOSTED_MODEL_ID = exports.MINIMAX_API_BASE_URL = exports.KIMI_CODING_MODEL_REF = void 0;
var synthetic_models_js_1 = require("../agents/synthetic-models.js");
Object.defineProperty(exports, "SYNTHETIC_DEFAULT_MODEL_ID", { enumerable: true, get: function () { return synthetic_models_js_1.SYNTHETIC_DEFAULT_MODEL_ID; } });
Object.defineProperty(exports, "SYNTHETIC_DEFAULT_MODEL_REF", { enumerable: true, get: function () { return synthetic_models_js_1.SYNTHETIC_DEFAULT_MODEL_REF; } });
var venice_models_js_1 = require("../agents/venice-models.js");
Object.defineProperty(exports, "VENICE_DEFAULT_MODEL_ID", { enumerable: true, get: function () { return venice_models_js_1.VENICE_DEFAULT_MODEL_ID; } });
Object.defineProperty(exports, "VENICE_DEFAULT_MODEL_REF", { enumerable: true, get: function () { return venice_models_js_1.VENICE_DEFAULT_MODEL_REF; } });
var onboard_auth_config_core_js_1 = require("./onboard-auth.config-core.js");
Object.defineProperty(exports, "applyAuthProfileConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyAuthProfileConfig; } });
Object.defineProperty(exports, "applyKimiCodeConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyKimiCodeConfig; } });
Object.defineProperty(exports, "applyKimiCodeProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyKimiCodeProviderConfig; } });
Object.defineProperty(exports, "applyMoonshotConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyMoonshotConfig; } });
Object.defineProperty(exports, "applyMoonshotProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyMoonshotProviderConfig; } });
Object.defineProperty(exports, "applyOpenrouterConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyOpenrouterConfig; } });
Object.defineProperty(exports, "applyOpenrouterProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyOpenrouterProviderConfig; } });
Object.defineProperty(exports, "applySyntheticConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applySyntheticConfig; } });
Object.defineProperty(exports, "applySyntheticProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applySyntheticProviderConfig; } });
Object.defineProperty(exports, "applyVeniceConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyVeniceConfig; } });
Object.defineProperty(exports, "applyVeniceProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyVeniceProviderConfig; } });
Object.defineProperty(exports, "applyVercelAiGatewayConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyVercelAiGatewayConfig; } });
Object.defineProperty(exports, "applyVercelAiGatewayProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyVercelAiGatewayProviderConfig; } });
Object.defineProperty(exports, "applyXiaomiConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyXiaomiConfig; } });
Object.defineProperty(exports, "applyXiaomiProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyXiaomiProviderConfig; } });
Object.defineProperty(exports, "applyZaiConfig", { enumerable: true, get: function () { return onboard_auth_config_core_js_1.applyZaiConfig; } });
var onboard_auth_config_minimax_js_1 = require("./onboard-auth.config-minimax.js");
Object.defineProperty(exports, "applyMinimaxApiConfig", { enumerable: true, get: function () { return onboard_auth_config_minimax_js_1.applyMinimaxApiConfig; } });
Object.defineProperty(exports, "applyMinimaxApiProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_minimax_js_1.applyMinimaxApiProviderConfig; } });
Object.defineProperty(exports, "applyMinimaxConfig", { enumerable: true, get: function () { return onboard_auth_config_minimax_js_1.applyMinimaxConfig; } });
Object.defineProperty(exports, "applyMinimaxHostedConfig", { enumerable: true, get: function () { return onboard_auth_config_minimax_js_1.applyMinimaxHostedConfig; } });
Object.defineProperty(exports, "applyMinimaxHostedProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_minimax_js_1.applyMinimaxHostedProviderConfig; } });
Object.defineProperty(exports, "applyMinimaxProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_minimax_js_1.applyMinimaxProviderConfig; } });
var onboard_auth_config_opencode_js_1 = require("./onboard-auth.config-opencode.js");
Object.defineProperty(exports, "applyOpencodeZenConfig", { enumerable: true, get: function () { return onboard_auth_config_opencode_js_1.applyOpencodeZenConfig; } });
Object.defineProperty(exports, "applyOpencodeZenProviderConfig", { enumerable: true, get: function () { return onboard_auth_config_opencode_js_1.applyOpencodeZenProviderConfig; } });
var onboard_auth_credentials_js_1 = require("./onboard-auth.credentials.js");
Object.defineProperty(exports, "OPENROUTER_DEFAULT_MODEL_REF", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.OPENROUTER_DEFAULT_MODEL_REF; } });
Object.defineProperty(exports, "setAnthropicApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setAnthropicApiKey; } });
Object.defineProperty(exports, "setGeminiApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setGeminiApiKey; } });
Object.defineProperty(exports, "setKimiCodingApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setKimiCodingApiKey; } });
Object.defineProperty(exports, "setMinimaxApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setMinimaxApiKey; } });
Object.defineProperty(exports, "setMoonshotApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setMoonshotApiKey; } });
Object.defineProperty(exports, "setOpencodeZenApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setOpencodeZenApiKey; } });
Object.defineProperty(exports, "setOpenrouterApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setOpenrouterApiKey; } });
Object.defineProperty(exports, "setSyntheticApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setSyntheticApiKey; } });
Object.defineProperty(exports, "setVeniceApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setVeniceApiKey; } });
Object.defineProperty(exports, "setVercelAiGatewayApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setVercelAiGatewayApiKey; } });
Object.defineProperty(exports, "setXiaomiApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setXiaomiApiKey; } });
Object.defineProperty(exports, "setZaiApiKey", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.setZaiApiKey; } });
Object.defineProperty(exports, "writeOAuthCredentials", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.writeOAuthCredentials; } });
Object.defineProperty(exports, "VERCEL_AI_GATEWAY_DEFAULT_MODEL_REF", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.VERCEL_AI_GATEWAY_DEFAULT_MODEL_REF; } });
Object.defineProperty(exports, "XIAOMI_DEFAULT_MODEL_REF", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.XIAOMI_DEFAULT_MODEL_REF; } });
Object.defineProperty(exports, "ZAI_DEFAULT_MODEL_REF", { enumerable: true, get: function () { return onboard_auth_credentials_js_1.ZAI_DEFAULT_MODEL_REF; } });
var onboard_auth_models_js_1 = require("./onboard-auth.models.js");
Object.defineProperty(exports, "buildMinimaxApiModelDefinition", { enumerable: true, get: function () { return onboard_auth_models_js_1.buildMinimaxApiModelDefinition; } });
Object.defineProperty(exports, "buildMinimaxModelDefinition", { enumerable: true, get: function () { return onboard_auth_models_js_1.buildMinimaxModelDefinition; } });
Object.defineProperty(exports, "buildMoonshotModelDefinition", { enumerable: true, get: function () { return onboard_auth_models_js_1.buildMoonshotModelDefinition; } });
Object.defineProperty(exports, "DEFAULT_MINIMAX_BASE_URL", { enumerable: true, get: function () { return onboard_auth_models_js_1.DEFAULT_MINIMAX_BASE_URL; } });
Object.defineProperty(exports, "KIMI_CODING_MODEL_ID", { enumerable: true, get: function () { return onboard_auth_models_js_1.KIMI_CODING_MODEL_ID; } });
Object.defineProperty(exports, "KIMI_CODING_MODEL_REF", { enumerable: true, get: function () { return onboard_auth_models_js_1.KIMI_CODING_MODEL_REF; } });
Object.defineProperty(exports, "MINIMAX_API_BASE_URL", { enumerable: true, get: function () { return onboard_auth_models_js_1.MINIMAX_API_BASE_URL; } });
Object.defineProperty(exports, "MINIMAX_HOSTED_MODEL_ID", { enumerable: true, get: function () { return onboard_auth_models_js_1.MINIMAX_HOSTED_MODEL_ID; } });
Object.defineProperty(exports, "MINIMAX_HOSTED_MODEL_REF", { enumerable: true, get: function () { return onboard_auth_models_js_1.MINIMAX_HOSTED_MODEL_REF; } });
Object.defineProperty(exports, "MOONSHOT_BASE_URL", { enumerable: true, get: function () { return onboard_auth_models_js_1.MOONSHOT_BASE_URL; } });
Object.defineProperty(exports, "MOONSHOT_DEFAULT_MODEL_ID", { enumerable: true, get: function () { return onboard_auth_models_js_1.MOONSHOT_DEFAULT_MODEL_ID; } });
Object.defineProperty(exports, "MOONSHOT_DEFAULT_MODEL_REF", { enumerable: true, get: function () { return onboard_auth_models_js_1.MOONSHOT_DEFAULT_MODEL_REF; } });
