"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __generator = (this && this.__generator) || function (thisArg, body) {
    var _ = { label: 0, sent: function() { if (t[0] & 1) throw t[1]; return t[1]; }, trys: [], ops: [] }, f, y, t, g = Object.create((typeof Iterator === "function" ? Iterator : Object).prototype);
    return g.next = verb(0), g["throw"] = verb(1), g["return"] = verb(2), typeof Symbol === "function" && (g[Symbol.iterator] = function() { return this; }), g;
    function verb(n) { return function (v) { return step([n, v]); }; }
    function step(op) {
        if (f) throw new TypeError("Generator is already executing.");
        while (g && (g = 0, op[0] && (_ = 0)), _) try {
            if (f = 1, y && (t = op[0] & 2 ? y["return"] : op[0] ? y["throw"] || ((t = y["return"]) && t.call(y), 0) : y.next) && !(t = t.call(y, op[1])).done) return t;
            if (y = 0, t) op = [op[0] & 2, t.value];
            switch (op[0]) {
                case 0: case 1: t = op; break;
                case 4: _.label++; return { value: op[1], done: false };
                case 5: _.label++; y = op[1]; op = [0]; continue;
                case 7: op = _.ops.pop(); _.trys.pop(); continue;
                default:
                    if (!(t = _.trys, t = t.length > 0 && t[t.length - 1]) && (op[0] === 6 || op[0] === 2)) { _ = 0; continue; }
                    if (op[0] === 3 && (!t || (op[1] > t[0] && op[1] < t[3]))) { _.label = op[1]; break; }
                    if (op[0] === 6 && _.label < t[1]) { _.label = t[1]; t = op; break; }
                    if (t && _.label < t[2]) { _.label = t[2]; _.ops.push(op); break; }
                    if (t[2]) _.ops.pop();
                    _.trys.pop(); continue;
            }
            op = body.call(thisArg, _);
        } catch (e) { op = [6, e]; y = 0; } finally { f = t = 0; }
        if (op[0] & 5) throw op[1]; return { value: op[0] ? op[1] : void 0, done: true };
    }
};
Object.defineProperty(exports, "__esModule", { value: true });
var node_fs_1 = require("node:fs");
var promises_1 = require("node:fs/promises");
var node_os_1 = require("node:os");
var node_path_1 = require("node:path");
var vitest_1 = require("vitest");
var chrome_js_1 = require("./chrome.js");
var constants_js_1 = require("./constants.js");
function readJson(filePath) {
    return __awaiter(this, void 0, void 0, function () {
        var raw;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, promises_1.default.readFile(filePath, "utf-8")];
                case 1:
                    raw = _a.sent();
                    return [2 /*return*/, JSON.parse(raw)];
            }
        });
    });
}
(0, vitest_1.describe)("browser chrome profile decoration", function () {
    (0, vitest_1.afterEach)(function () {
        vitest_1.vi.unstubAllGlobals();
        vitest_1.vi.restoreAllMocks();
    });
    (0, vitest_1.it)("writes expected name + signed ARGB seed to Chrome prefs", function () { return __awaiter(void 0, void 0, void 0, function () {
        var userDataDir, expectedSignedArgb, localState, profile, infoCache, def, prefs, browser, theme, autogenerated, autogeneratedTheme, marker;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, promises_1.default.mkdtemp(node_path_1.default.join(node_os_1.default.tmpdir(), "openclaw-chrome-test-"))];
                case 1:
                    userDataDir = _a.sent();
                    _a.label = 2;
                case 2:
                    _a.trys.push([2, , 6, 8]);
                    (0, chrome_js_1.decorateOpenClawProfile)(userDataDir, { color: constants_js_1.DEFAULT_OPENCLAW_BROWSER_COLOR });
                    expectedSignedArgb = ((0xff << 24) | 0xff4500) >> 0;
                    return [4 /*yield*/, readJson(node_path_1.default.join(userDataDir, "Local State"))];
                case 3:
                    localState = _a.sent();
                    profile = localState.profile;
                    infoCache = profile.info_cache;
                    def = infoCache.Default;
                    (0, vitest_1.expect)(def.name).toBe(constants_js_1.DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME);
                    (0, vitest_1.expect)(def.shortcut_name).toBe(constants_js_1.DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME);
                    (0, vitest_1.expect)(def.profile_color_seed).toBe(expectedSignedArgb);
                    (0, vitest_1.expect)(def.profile_highlight_color).toBe(expectedSignedArgb);
                    (0, vitest_1.expect)(def.default_avatar_fill_color).toBe(expectedSignedArgb);
                    (0, vitest_1.expect)(def.default_avatar_stroke_color).toBe(expectedSignedArgb);
                    return [4 /*yield*/, readJson(node_path_1.default.join(userDataDir, "Default", "Preferences"))];
                case 4:
                    prefs = _a.sent();
                    browser = prefs.browser;
                    theme = browser.theme;
                    autogenerated = prefs.autogenerated;
                    autogeneratedTheme = autogenerated.theme;
                    (0, vitest_1.expect)(theme.user_color2).toBe(expectedSignedArgb);
                    (0, vitest_1.expect)(autogeneratedTheme.color).toBe(expectedSignedArgb);
                    return [4 /*yield*/, promises_1.default.readFile(node_path_1.default.join(userDataDir, ".openclaw-profile-decorated"), "utf-8")];
                case 5:
                    marker = _a.sent();
                    (0, vitest_1.expect)(marker.trim()).toMatch(/^\d+$/);
                    return [3 /*break*/, 8];
                case 6: return [4 /*yield*/, promises_1.default.rm(userDataDir, { recursive: true, force: true })];
                case 7:
                    _a.sent();
                    return [7 /*endfinally*/];
                case 8: return [2 /*return*/];
            }
        });
    }); });
    (0, vitest_1.it)("best-effort writes name when color is invalid", function () { return __awaiter(void 0, void 0, void 0, function () {
        var userDataDir, localState, profile, infoCache, def;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, promises_1.default.mkdtemp(node_path_1.default.join(node_os_1.default.tmpdir(), "openclaw-chrome-test-"))];
                case 1:
                    userDataDir = _a.sent();
                    _a.label = 2;
                case 2:
                    _a.trys.push([2, , 4, 6]);
                    (0, chrome_js_1.decorateOpenClawProfile)(userDataDir, { color: "lobster-orange" });
                    return [4 /*yield*/, readJson(node_path_1.default.join(userDataDir, "Local State"))];
                case 3:
                    localState = _a.sent();
                    profile = localState.profile;
                    infoCache = profile.info_cache;
                    def = infoCache.Default;
                    (0, vitest_1.expect)(def.name).toBe(constants_js_1.DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME);
                    (0, vitest_1.expect)(def.profile_color_seed).toBeUndefined();
                    return [3 /*break*/, 6];
                case 4: return [4 /*yield*/, promises_1.default.rm(userDataDir, { recursive: true, force: true })];
                case 5:
                    _a.sent();
                    return [7 /*endfinally*/];
                case 6: return [2 /*return*/];
            }
        });
    }); });
    (0, vitest_1.it)("recovers from missing/invalid preference files", function () { return __awaiter(void 0, void 0, void 0, function () {
        var userDataDir, localState, prefs;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, promises_1.default.mkdtemp(node_path_1.default.join(node_os_1.default.tmpdir(), "openclaw-chrome-test-"))];
                case 1:
                    userDataDir = _a.sent();
                    _a.label = 2;
                case 2:
                    _a.trys.push([2, , 8, 10]);
                    return [4 /*yield*/, promises_1.default.mkdir(node_path_1.default.join(userDataDir, "Default"), { recursive: true })];
                case 3:
                    _a.sent();
                    return [4 /*yield*/, promises_1.default.writeFile(node_path_1.default.join(userDataDir, "Local State"), "{", "utf-8")];
                case 4:
                    _a.sent(); // invalid JSON
                    return [4 /*yield*/, promises_1.default.writeFile(node_path_1.default.join(userDataDir, "Default", "Preferences"), "[]", // valid JSON but wrong shape
                        "utf-8")];
                case 5:
                    _a.sent();
                    (0, chrome_js_1.decorateOpenClawProfile)(userDataDir, { color: constants_js_1.DEFAULT_OPENCLAW_BROWSER_COLOR });
                    return [4 /*yield*/, readJson(node_path_1.default.join(userDataDir, "Local State"))];
                case 6:
                    localState = _a.sent();
                    (0, vitest_1.expect)(typeof localState.profile).toBe("object");
                    return [4 /*yield*/, readJson(node_path_1.default.join(userDataDir, "Default", "Preferences"))];
                case 7:
                    prefs = _a.sent();
                    (0, vitest_1.expect)(typeof prefs.profile).toBe("object");
                    return [3 /*break*/, 10];
                case 8: return [4 /*yield*/, promises_1.default.rm(userDataDir, { recursive: true, force: true })];
                case 9:
                    _a.sent();
                    return [7 /*endfinally*/];
                case 10: return [2 /*return*/];
            }
        });
    }); });
    (0, vitest_1.it)("writes clean exit prefs to avoid restore prompts", function () { return __awaiter(void 0, void 0, void 0, function () {
        var userDataDir, prefs;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, promises_1.default.mkdtemp(node_path_1.default.join(node_os_1.default.tmpdir(), "openclaw-chrome-test-"))];
                case 1:
                    userDataDir = _a.sent();
                    _a.label = 2;
                case 2:
                    _a.trys.push([2, , 4, 6]);
                    (0, chrome_js_1.ensureProfileCleanExit)(userDataDir);
                    return [4 /*yield*/, readJson(node_path_1.default.join(userDataDir, "Default", "Preferences"))];
                case 3:
                    prefs = _a.sent();
                    (0, vitest_1.expect)(prefs.exit_type).toBe("Normal");
                    (0, vitest_1.expect)(prefs.exited_cleanly).toBe(true);
                    return [3 /*break*/, 6];
                case 4: return [4 /*yield*/, promises_1.default.rm(userDataDir, { recursive: true, force: true })];
                case 5:
                    _a.sent();
                    return [7 /*endfinally*/];
                case 6: return [2 /*return*/];
            }
        });
    }); });
    (0, vitest_1.it)("is idempotent when rerun on an existing profile", function () { return __awaiter(void 0, void 0, void 0, function () {
        var userDataDir, prefs, profile;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0: return [4 /*yield*/, promises_1.default.mkdtemp(node_path_1.default.join(node_os_1.default.tmpdir(), "openclaw-chrome-test-"))];
                case 1:
                    userDataDir = _a.sent();
                    _a.label = 2;
                case 2:
                    _a.trys.push([2, , 4, 6]);
                    (0, chrome_js_1.decorateOpenClawProfile)(userDataDir, { color: constants_js_1.DEFAULT_OPENCLAW_BROWSER_COLOR });
                    (0, chrome_js_1.decorateOpenClawProfile)(userDataDir, { color: constants_js_1.DEFAULT_OPENCLAW_BROWSER_COLOR });
                    return [4 /*yield*/, readJson(node_path_1.default.join(userDataDir, "Default", "Preferences"))];
                case 3:
                    prefs = _a.sent();
                    profile = prefs.profile;
                    (0, vitest_1.expect)(profile.name).toBe(constants_js_1.DEFAULT_OPENCLAW_BROWSER_PROFILE_NAME);
                    return [3 /*break*/, 6];
                case 4: return [4 /*yield*/, promises_1.default.rm(userDataDir, { recursive: true, force: true })];
                case 5:
                    _a.sent();
                    return [7 /*endfinally*/];
                case 6: return [2 /*return*/];
            }
        });
    }); });
});
(0, vitest_1.describe)("browser chrome helpers", function () {
    (0, vitest_1.afterEach)(function () {
        vitest_1.vi.unstubAllEnvs();
        vitest_1.vi.unstubAllGlobals();
        vitest_1.vi.restoreAllMocks();
    });
    (0, vitest_1.it)("picks the first existing Chrome candidate on macOS", function () {
        var exists = vitest_1.vi
            .spyOn(node_fs_1.default, "existsSync")
            .mockImplementation(function (p) {
            return String(p).includes("Google Chrome.app/Contents/MacOS/Google Chrome");
        });
        var exe = (0, chrome_js_1.findChromeExecutableMac)();
        (0, vitest_1.expect)(exe === null || exe === void 0 ? void 0 : exe.kind).toBe("chrome");
        (0, vitest_1.expect)(exe === null || exe === void 0 ? void 0 : exe.path).toMatch(/Google Chrome\.app/);
        exists.mockRestore();
    });
    (0, vitest_1.it)("returns null when no Chrome candidate exists", function () {
        var exists = vitest_1.vi.spyOn(node_fs_1.default, "existsSync").mockReturnValue(false);
        (0, vitest_1.expect)((0, chrome_js_1.findChromeExecutableMac)()).toBeNull();
        exists.mockRestore();
    });
    (0, vitest_1.it)("picks the first existing Chrome candidate on Windows", function () {
        vitest_1.vi.stubEnv("LOCALAPPDATA", "C:\\Users\\Test\\AppData\\Local");
        var exists = vitest_1.vi.spyOn(node_fs_1.default, "existsSync").mockImplementation(function (p) {
            var pathStr = String(p);
            return (pathStr.includes("Google\\Chrome\\Application\\chrome.exe") ||
                pathStr.includes("BraveSoftware\\Brave-Browser\\Application\\brave.exe") ||
                pathStr.includes("Microsoft\\Edge\\Application\\msedge.exe"));
        });
        var exe = (0, chrome_js_1.findChromeExecutableWindows)();
        (0, vitest_1.expect)(exe === null || exe === void 0 ? void 0 : exe.kind).toBe("chrome");
        (0, vitest_1.expect)(exe === null || exe === void 0 ? void 0 : exe.path).toMatch(/chrome\.exe$/);
        exists.mockRestore();
    });
    (0, vitest_1.it)("finds Chrome in Program Files on Windows", function () {
        var marker = node_path_1.default.win32.join("Program Files", "Google", "Chrome");
        var exists = vitest_1.vi.spyOn(node_fs_1.default, "existsSync").mockImplementation(function (p) { return String(p).includes(marker); });
        var exe = (0, chrome_js_1.findChromeExecutableWindows)();
        (0, vitest_1.expect)(exe === null || exe === void 0 ? void 0 : exe.kind).toBe("chrome");
        (0, vitest_1.expect)(exe === null || exe === void 0 ? void 0 : exe.path).toMatch(/chrome\.exe$/);
        exists.mockRestore();
    });
    (0, vitest_1.it)("returns null when no Chrome candidate exists on Windows", function () {
        var exists = vitest_1.vi.spyOn(node_fs_1.default, "existsSync").mockReturnValue(false);
        (0, vitest_1.expect)((0, chrome_js_1.findChromeExecutableWindows)()).toBeNull();
        exists.mockRestore();
    });
    (0, vitest_1.it)("resolves Windows executables without LOCALAPPDATA", function () {
        vitest_1.vi.stubEnv("LOCALAPPDATA", "");
        vitest_1.vi.stubEnv("ProgramFiles", "C:\\Program Files");
        vitest_1.vi.stubEnv("ProgramFiles(x86)", "C:\\Program Files (x86)");
        var marker = node_path_1.default.win32.join("Program Files", "Google", "Chrome", "Application", "chrome.exe");
        var exists = vitest_1.vi.spyOn(node_fs_1.default, "existsSync").mockImplementation(function (p) { return String(p).includes(marker); });
        var exe = (0, chrome_js_1.resolveBrowserExecutableForPlatform)({}, "win32");
        (0, vitest_1.expect)(exe === null || exe === void 0 ? void 0 : exe.kind).toBe("chrome");
        (0, vitest_1.expect)(exe === null || exe === void 0 ? void 0 : exe.path).toMatch(/chrome\.exe$/);
        exists.mockRestore();
    });
    (0, vitest_1.it)("reports reachability based on /json/version", function () { return __awaiter(void 0, void 0, void 0, function () {
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    vitest_1.vi.stubGlobal("fetch", vitest_1.vi.fn().mockResolvedValue({
                        ok: true,
                        json: function () { return __awaiter(void 0, void 0, void 0, function () { return __generator(this, function (_a) {
                            return [2 /*return*/, ({ webSocketDebuggerUrl: "ws://127.0.0.1/devtools" })];
                        }); }); },
                    }));
                    return [4 /*yield*/, (0, vitest_1.expect)((0, chrome_js_1.isChromeReachable)("http://127.0.0.1:12345", 50)).resolves.toBe(true)];
                case 1:
                    _a.sent();
                    vitest_1.vi.stubGlobal("fetch", vitest_1.vi.fn().mockResolvedValue({
                        ok: false,
                        json: function () { return __awaiter(void 0, void 0, void 0, function () { return __generator(this, function (_a) {
                            return [2 /*return*/, ({})];
                        }); }); },
                    }));
                    return [4 /*yield*/, (0, vitest_1.expect)((0, chrome_js_1.isChromeReachable)("http://127.0.0.1:12345", 50)).resolves.toBe(false)];
                case 2:
                    _a.sent();
                    vitest_1.vi.stubGlobal("fetch", vitest_1.vi.fn().mockRejectedValue(new Error("boom")));
                    return [4 /*yield*/, (0, vitest_1.expect)((0, chrome_js_1.isChromeReachable)("http://127.0.0.1:12345", 50)).resolves.toBe(false)];
                case 3:
                    _a.sent();
                    return [2 /*return*/];
            }
        });
    }); });
    (0, vitest_1.it)("stopOpenClawChrome no-ops when process is already killed", function () { return __awaiter(void 0, void 0, void 0, function () {
        var proc;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    proc = { killed: true, exitCode: null, kill: vitest_1.vi.fn() };
                    return [4 /*yield*/, (0, chrome_js_1.stopOpenClawChrome)({
                            proc: proc,
                            cdpPort: 12345,
                        }, 10)];
                case 1:
                    _a.sent();
                    (0, vitest_1.expect)(proc.kill).not.toHaveBeenCalled();
                    return [2 /*return*/];
            }
        });
    }); });
    (0, vitest_1.it)("stopOpenClawChrome sends SIGTERM and returns once CDP is down", function () { return __awaiter(void 0, void 0, void 0, function () {
        var proc;
        return __generator(this, function (_a) {
            switch (_a.label) {
                case 0:
                    vitest_1.vi.stubGlobal("fetch", vitest_1.vi.fn().mockRejectedValue(new Error("down")));
                    proc = { killed: false, exitCode: null, kill: vitest_1.vi.fn() };
                    return [4 /*yield*/, (0, chrome_js_1.stopOpenClawChrome)({
                            proc: proc,
                            cdpPort: 12345,
                        }, 10)];
                case 1:
                    _a.sent();
                    (0, vitest_1.expect)(proc.kill).toHaveBeenCalledWith("SIGTERM");
                    return [2 /*return*/];
            }
        });
    }); });
});
