"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.resolveChannelMediaMaxBytes = exports.logTypingFailure = exports.logInboundDrop = exports.logAckFailure = exports.createReplyPrefixContext = exports.createTypingCallbacks = exports.shouldAckReactionForWhatsApp = exports.shouldAckReaction = exports.removeAckReactionAfterReply = exports.resolveMentionGatingWithBypass = exports.resolveMentionGating = exports.summarizeMapping = exports.mergeAllowlist = exports.recordPendingHistoryEntryIfEnabled = exports.recordPendingHistoryEntry = exports.DEFAULT_GROUP_HISTORY_LIMIT = exports.clearHistoryEntriesIfEnabled = exports.clearHistoryEntries = exports.buildPendingHistoryContextFromMap = exports.resolveToolsBySender = exports.isSilentReplyText = exports.SILENT_REPLY_TOKEN = exports.resolveAckReaction = exports.normalizeAccountId = exports.DEFAULT_ACCOUNT_ID = exports.ToolPolicySchema = exports.requireOpenAllowFrom = exports.normalizeAllowFrom = exports.MarkdownTableModeSchema = exports.MarkdownConfigSchema = exports.GroupPolicySchema = exports.DmPolicySchema = exports.DmConfigSchema = exports.BlockStreamingCoalesceSchema = exports.WhatsAppConfigSchema = exports.TelegramConfigSchema = exports.SlackConfigSchema = exports.SignalConfigSchema = exports.MSTeamsConfigSchema = exports.IMessageConfigSchema = exports.GoogleChatConfigSchema = exports.DiscordConfigSchema = exports.getChatChannelMeta = exports.emptyPluginConfigSchema = exports.registerPluginHttpRoute = exports.normalizePluginHttpPath = exports.BLUEBUBBLES_GROUP_ACTIONS = exports.BLUEBUBBLES_ACTION_NAMES = exports.BLUEBUBBLES_ACTIONS = exports.CHANNEL_MESSAGE_ACTION_NAMES = void 0;
exports.formatDocsLink = exports.readStringParam = exports.readReactionParams = exports.readNumberParam = exports.jsonResult = exports.createActionGate = exports.promptChannelAccessConfig = exports.promptAccountId = exports.addWildcardAllowFrom = exports.PAIRING_APPROVED_MESSAGE = exports.formatPairingApproveHint = exports.migrateBaseNameToDefaultAccount = exports.applyAccountNameToChannelSection = exports.setAccountEnabledInConfigSection = exports.deleteAccountFromConfigSection = exports.buildChannelConfigSchema = exports.stringEnum = exports.optionalStringEnum = exports.formatAllowlistMatchMeta = exports.listWhatsAppDirectoryPeersFromConfig = exports.listWhatsAppDirectoryGroupsFromConfig = exports.listTelegramDirectoryPeersFromConfig = exports.listTelegramDirectoryGroupsFromConfig = exports.listSlackDirectoryPeersFromConfig = exports.listSlackDirectoryGroupsFromConfig = exports.listDiscordDirectoryPeersFromConfig = exports.listDiscordDirectoryGroupsFromConfig = exports.resolveNestedAllowlistDecision = exports.resolveChannelEntryMatchWithFallback = exports.resolveChannelEntryMatch = exports.normalizeChannelSlug = exports.buildChannelKeyCandidates = exports.recordInboundSession = exports.resolveWhatsAppGroupToolPolicy = exports.resolveTelegramGroupToolPolicy = exports.resolveSlackGroupToolPolicy = exports.resolveIMessageGroupToolPolicy = exports.resolveGoogleChatGroupToolPolicy = exports.resolveDiscordGroupToolPolicy = exports.resolveBlueBubblesGroupToolPolicy = exports.resolveWhatsAppGroupRequireMention = exports.resolveTelegramGroupRequireMention = exports.resolveSlackGroupRequireMention = exports.resolveIMessageGroupRequireMention = exports.resolveGoogleChatGroupRequireMention = exports.resolveDiscordGroupRequireMention = exports.resolveBlueBubblesGroupRequireMention = exports.resolveControlCommandGate = exports.toLocationContext = exports.formatLocationText = void 0;
exports.isWhatsAppGroupJid = exports.resolveWhatsAppAccount = exports.resolveDefaultWhatsAppAccountId = exports.listWhatsAppAccountIds = exports.normalizeSignalMessagingTarget = exports.looksLikeSignalTargetId = exports.signalOnboardingAdapter = exports.resolveSignalAccount = exports.resolveDefaultSignalAccountId = exports.listSignalAccountIds = exports.collectTelegramStatusIssues = exports.normalizeTelegramMessagingTarget = exports.looksLikeTelegramTargetId = exports.telegramOnboardingAdapter = exports.resolveTelegramAccount = exports.resolveDefaultTelegramAccountId = exports.listTelegramAccountIds = exports.buildSlackThreadingToolContext = exports.normalizeSlackMessagingTarget = exports.looksLikeSlackTargetId = exports.slackOnboardingAdapter = exports.resolveSlackReplyToMode = exports.resolveSlackAccount = exports.resolveDefaultSlackAccountId = exports.listSlackAccountIds = exports.listEnabledSlackAccounts = exports.normalizeIMessageMessagingTarget = exports.looksLikeIMessageTargetId = exports.imessageOnboardingAdapter = exports.resolveIMessageAccount = exports.resolveDefaultIMessageAccountId = exports.listIMessageAccountIds = exports.collectDiscordStatusIssues = exports.normalizeDiscordMessagingTarget = exports.looksLikeDiscordTargetId = exports.discordOnboardingAdapter = exports.collectDiscordAuditChannelIds = exports.resolveDiscordAccount = exports.resolveDefaultDiscordAccountId = exports.listDiscordAccountIds = exports.extractOriginalFilename = exports.getFileExtension = exports.extensionForMime = exports.detectMime = exports.onDiagnosticEvent = exports.isDiagnosticsEnabled = exports.emitDiagnosticEvent = exports.registerLogTransport = exports.missingTargetError = exports.normalizeE164 = void 0;
exports.loadWebMedia = exports.stripMarkdown = exports.hasMarkdownToConvert = exports.processLineMessage = exports.createReceiptCard = exports.createActionCard = exports.createImageCard = exports.createListCard = exports.createInfoCard = exports.LineConfigSchema = exports.resolveLineAccount = exports.resolveDefaultLineAccountId = exports.normalizeLineAccountId = exports.listLineAccountIds = exports.collectBlueBubblesStatusIssues = exports.collectWhatsAppStatusIssues = exports.normalizeWhatsAppMessagingTarget = exports.looksLikeWhatsAppTargetId = exports.resolveWhatsAppHeartbeatRecipients = exports.whatsappOnboardingAdapter = exports.normalizeWhatsAppTarget = void 0;
var message_action_names_js_1 = require("../channels/plugins/message-action-names.js");
Object.defineProperty(exports, "CHANNEL_MESSAGE_ACTION_NAMES", { enumerable: true, get: function () { return message_action_names_js_1.CHANNEL_MESSAGE_ACTION_NAMES; } });
var bluebubbles_actions_js_1 = require("../channels/plugins/bluebubbles-actions.js");
Object.defineProperty(exports, "BLUEBUBBLES_ACTIONS", { enumerable: true, get: function () { return bluebubbles_actions_js_1.BLUEBUBBLES_ACTIONS; } });
Object.defineProperty(exports, "BLUEBUBBLES_ACTION_NAMES", { enumerable: true, get: function () { return bluebubbles_actions_js_1.BLUEBUBBLES_ACTION_NAMES; } });
Object.defineProperty(exports, "BLUEBUBBLES_GROUP_ACTIONS", { enumerable: true, get: function () { return bluebubbles_actions_js_1.BLUEBUBBLES_GROUP_ACTIONS; } });
var http_path_js_1 = require("../plugins/http-path.js");
Object.defineProperty(exports, "normalizePluginHttpPath", { enumerable: true, get: function () { return http_path_js_1.normalizePluginHttpPath; } });
var http_registry_js_1 = require("../plugins/http-registry.js");
Object.defineProperty(exports, "registerPluginHttpRoute", { enumerable: true, get: function () { return http_registry_js_1.registerPluginHttpRoute; } });
var config_schema_js_1 = require("../plugins/config-schema.js");
Object.defineProperty(exports, "emptyPluginConfigSchema", { enumerable: true, get: function () { return config_schema_js_1.emptyPluginConfigSchema; } });
var registry_js_1 = require("../channels/registry.js");
Object.defineProperty(exports, "getChatChannelMeta", { enumerable: true, get: function () { return registry_js_1.getChatChannelMeta; } });
var zod_schema_providers_core_js_1 = require("../config/zod-schema.providers-core.js");
Object.defineProperty(exports, "DiscordConfigSchema", { enumerable: true, get: function () { return zod_schema_providers_core_js_1.DiscordConfigSchema; } });
Object.defineProperty(exports, "GoogleChatConfigSchema", { enumerable: true, get: function () { return zod_schema_providers_core_js_1.GoogleChatConfigSchema; } });
Object.defineProperty(exports, "IMessageConfigSchema", { enumerable: true, get: function () { return zod_schema_providers_core_js_1.IMessageConfigSchema; } });
Object.defineProperty(exports, "MSTeamsConfigSchema", { enumerable: true, get: function () { return zod_schema_providers_core_js_1.MSTeamsConfigSchema; } });
Object.defineProperty(exports, "SignalConfigSchema", { enumerable: true, get: function () { return zod_schema_providers_core_js_1.SignalConfigSchema; } });
Object.defineProperty(exports, "SlackConfigSchema", { enumerable: true, get: function () { return zod_schema_providers_core_js_1.SlackConfigSchema; } });
Object.defineProperty(exports, "TelegramConfigSchema", { enumerable: true, get: function () { return zod_schema_providers_core_js_1.TelegramConfigSchema; } });
var zod_schema_providers_whatsapp_js_1 = require("../config/zod-schema.providers-whatsapp.js");
Object.defineProperty(exports, "WhatsAppConfigSchema", { enumerable: true, get: function () { return zod_schema_providers_whatsapp_js_1.WhatsAppConfigSchema; } });
var zod_schema_core_js_1 = require("../config/zod-schema.core.js");
Object.defineProperty(exports, "BlockStreamingCoalesceSchema", { enumerable: true, get: function () { return zod_schema_core_js_1.BlockStreamingCoalesceSchema; } });
Object.defineProperty(exports, "DmConfigSchema", { enumerable: true, get: function () { return zod_schema_core_js_1.DmConfigSchema; } });
Object.defineProperty(exports, "DmPolicySchema", { enumerable: true, get: function () { return zod_schema_core_js_1.DmPolicySchema; } });
Object.defineProperty(exports, "GroupPolicySchema", { enumerable: true, get: function () { return zod_schema_core_js_1.GroupPolicySchema; } });
Object.defineProperty(exports, "MarkdownConfigSchema", { enumerable: true, get: function () { return zod_schema_core_js_1.MarkdownConfigSchema; } });
Object.defineProperty(exports, "MarkdownTableModeSchema", { enumerable: true, get: function () { return zod_schema_core_js_1.MarkdownTableModeSchema; } });
Object.defineProperty(exports, "normalizeAllowFrom", { enumerable: true, get: function () { return zod_schema_core_js_1.normalizeAllowFrom; } });
Object.defineProperty(exports, "requireOpenAllowFrom", { enumerable: true, get: function () { return zod_schema_core_js_1.requireOpenAllowFrom; } });
var zod_schema_agent_runtime_js_1 = require("../config/zod-schema.agent-runtime.js");
Object.defineProperty(exports, "ToolPolicySchema", { enumerable: true, get: function () { return zod_schema_agent_runtime_js_1.ToolPolicySchema; } });
var session_key_js_1 = require("../routing/session-key.js");
Object.defineProperty(exports, "DEFAULT_ACCOUNT_ID", { enumerable: true, get: function () { return session_key_js_1.DEFAULT_ACCOUNT_ID; } });
Object.defineProperty(exports, "normalizeAccountId", { enumerable: true, get: function () { return session_key_js_1.normalizeAccountId; } });
var identity_js_1 = require("../agents/identity.js");
Object.defineProperty(exports, "resolveAckReaction", { enumerable: true, get: function () { return identity_js_1.resolveAckReaction; } });
var tokens_js_1 = require("../auto-reply/tokens.js");
Object.defineProperty(exports, "SILENT_REPLY_TOKEN", { enumerable: true, get: function () { return tokens_js_1.SILENT_REPLY_TOKEN; } });
Object.defineProperty(exports, "isSilentReplyText", { enumerable: true, get: function () { return tokens_js_1.isSilentReplyText; } });
var group_policy_js_1 = require("../config/group-policy.js");
Object.defineProperty(exports, "resolveToolsBySender", { enumerable: true, get: function () { return group_policy_js_1.resolveToolsBySender; } });
var history_js_1 = require("../auto-reply/reply/history.js");
Object.defineProperty(exports, "buildPendingHistoryContextFromMap", { enumerable: true, get: function () { return history_js_1.buildPendingHistoryContextFromMap; } });
Object.defineProperty(exports, "clearHistoryEntries", { enumerable: true, get: function () { return history_js_1.clearHistoryEntries; } });
Object.defineProperty(exports, "clearHistoryEntriesIfEnabled", { enumerable: true, get: function () { return history_js_1.clearHistoryEntriesIfEnabled; } });
Object.defineProperty(exports, "DEFAULT_GROUP_HISTORY_LIMIT", { enumerable: true, get: function () { return history_js_1.DEFAULT_GROUP_HISTORY_LIMIT; } });
Object.defineProperty(exports, "recordPendingHistoryEntry", { enumerable: true, get: function () { return history_js_1.recordPendingHistoryEntry; } });
Object.defineProperty(exports, "recordPendingHistoryEntryIfEnabled", { enumerable: true, get: function () { return history_js_1.recordPendingHistoryEntryIfEnabled; } });
var resolve_utils_js_1 = require("../channels/allowlists/resolve-utils.js");
Object.defineProperty(exports, "mergeAllowlist", { enumerable: true, get: function () { return resolve_utils_js_1.mergeAllowlist; } });
Object.defineProperty(exports, "summarizeMapping", { enumerable: true, get: function () { return resolve_utils_js_1.summarizeMapping; } });
var mention_gating_js_1 = require("../channels/mention-gating.js");
Object.defineProperty(exports, "resolveMentionGating", { enumerable: true, get: function () { return mention_gating_js_1.resolveMentionGating; } });
Object.defineProperty(exports, "resolveMentionGatingWithBypass", { enumerable: true, get: function () { return mention_gating_js_1.resolveMentionGatingWithBypass; } });
var ack_reactions_js_1 = require("../channels/ack-reactions.js");
Object.defineProperty(exports, "removeAckReactionAfterReply", { enumerable: true, get: function () { return ack_reactions_js_1.removeAckReactionAfterReply; } });
Object.defineProperty(exports, "shouldAckReaction", { enumerable: true, get: function () { return ack_reactions_js_1.shouldAckReaction; } });
Object.defineProperty(exports, "shouldAckReactionForWhatsApp", { enumerable: true, get: function () { return ack_reactions_js_1.shouldAckReactionForWhatsApp; } });
var typing_js_1 = require("../channels/typing.js");
Object.defineProperty(exports, "createTypingCallbacks", { enumerable: true, get: function () { return typing_js_1.createTypingCallbacks; } });
var reply_prefix_js_1 = require("../channels/reply-prefix.js");
Object.defineProperty(exports, "createReplyPrefixContext", { enumerable: true, get: function () { return reply_prefix_js_1.createReplyPrefixContext; } });
var logging_js_1 = require("../channels/logging.js");
Object.defineProperty(exports, "logAckFailure", { enumerable: true, get: function () { return logging_js_1.logAckFailure; } });
Object.defineProperty(exports, "logInboundDrop", { enumerable: true, get: function () { return logging_js_1.logInboundDrop; } });
Object.defineProperty(exports, "logTypingFailure", { enumerable: true, get: function () { return logging_js_1.logTypingFailure; } });
var media_limits_js_1 = require("../channels/plugins/media-limits.js");
Object.defineProperty(exports, "resolveChannelMediaMaxBytes", { enumerable: true, get: function () { return media_limits_js_1.resolveChannelMediaMaxBytes; } });
var location_js_1 = require("../channels/location.js");
Object.defineProperty(exports, "formatLocationText", { enumerable: true, get: function () { return location_js_1.formatLocationText; } });
Object.defineProperty(exports, "toLocationContext", { enumerable: true, get: function () { return location_js_1.toLocationContext; } });
var command_gating_js_1 = require("../channels/command-gating.js");
Object.defineProperty(exports, "resolveControlCommandGate", { enumerable: true, get: function () { return command_gating_js_1.resolveControlCommandGate; } });
var group_mentions_js_1 = require("../channels/plugins/group-mentions.js");
Object.defineProperty(exports, "resolveBlueBubblesGroupRequireMention", { enumerable: true, get: function () { return group_mentions_js_1.resolveBlueBubblesGroupRequireMention; } });
Object.defineProperty(exports, "resolveDiscordGroupRequireMention", { enumerable: true, get: function () { return group_mentions_js_1.resolveDiscordGroupRequireMention; } });
Object.defineProperty(exports, "resolveGoogleChatGroupRequireMention", { enumerable: true, get: function () { return group_mentions_js_1.resolveGoogleChatGroupRequireMention; } });
Object.defineProperty(exports, "resolveIMessageGroupRequireMention", { enumerable: true, get: function () { return group_mentions_js_1.resolveIMessageGroupRequireMention; } });
Object.defineProperty(exports, "resolveSlackGroupRequireMention", { enumerable: true, get: function () { return group_mentions_js_1.resolveSlackGroupRequireMention; } });
Object.defineProperty(exports, "resolveTelegramGroupRequireMention", { enumerable: true, get: function () { return group_mentions_js_1.resolveTelegramGroupRequireMention; } });
Object.defineProperty(exports, "resolveWhatsAppGroupRequireMention", { enumerable: true, get: function () { return group_mentions_js_1.resolveWhatsAppGroupRequireMention; } });
Object.defineProperty(exports, "resolveBlueBubblesGroupToolPolicy", { enumerable: true, get: function () { return group_mentions_js_1.resolveBlueBubblesGroupToolPolicy; } });
Object.defineProperty(exports, "resolveDiscordGroupToolPolicy", { enumerable: true, get: function () { return group_mentions_js_1.resolveDiscordGroupToolPolicy; } });
Object.defineProperty(exports, "resolveGoogleChatGroupToolPolicy", { enumerable: true, get: function () { return group_mentions_js_1.resolveGoogleChatGroupToolPolicy; } });
Object.defineProperty(exports, "resolveIMessageGroupToolPolicy", { enumerable: true, get: function () { return group_mentions_js_1.resolveIMessageGroupToolPolicy; } });
Object.defineProperty(exports, "resolveSlackGroupToolPolicy", { enumerable: true, get: function () { return group_mentions_js_1.resolveSlackGroupToolPolicy; } });
Object.defineProperty(exports, "resolveTelegramGroupToolPolicy", { enumerable: true, get: function () { return group_mentions_js_1.resolveTelegramGroupToolPolicy; } });
Object.defineProperty(exports, "resolveWhatsAppGroupToolPolicy", { enumerable: true, get: function () { return group_mentions_js_1.resolveWhatsAppGroupToolPolicy; } });
var session_js_1 = require("../channels/session.js");
Object.defineProperty(exports, "recordInboundSession", { enumerable: true, get: function () { return session_js_1.recordInboundSession; } });
var channel_config_js_1 = require("../channels/plugins/channel-config.js");
Object.defineProperty(exports, "buildChannelKeyCandidates", { enumerable: true, get: function () { return channel_config_js_1.buildChannelKeyCandidates; } });
Object.defineProperty(exports, "normalizeChannelSlug", { enumerable: true, get: function () { return channel_config_js_1.normalizeChannelSlug; } });
Object.defineProperty(exports, "resolveChannelEntryMatch", { enumerable: true, get: function () { return channel_config_js_1.resolveChannelEntryMatch; } });
Object.defineProperty(exports, "resolveChannelEntryMatchWithFallback", { enumerable: true, get: function () { return channel_config_js_1.resolveChannelEntryMatchWithFallback; } });
Object.defineProperty(exports, "resolveNestedAllowlistDecision", { enumerable: true, get: function () { return channel_config_js_1.resolveNestedAllowlistDecision; } });
var directory_config_js_1 = require("../channels/plugins/directory-config.js");
Object.defineProperty(exports, "listDiscordDirectoryGroupsFromConfig", { enumerable: true, get: function () { return directory_config_js_1.listDiscordDirectoryGroupsFromConfig; } });
Object.defineProperty(exports, "listDiscordDirectoryPeersFromConfig", { enumerable: true, get: function () { return directory_config_js_1.listDiscordDirectoryPeersFromConfig; } });
Object.defineProperty(exports, "listSlackDirectoryGroupsFromConfig", { enumerable: true, get: function () { return directory_config_js_1.listSlackDirectoryGroupsFromConfig; } });
Object.defineProperty(exports, "listSlackDirectoryPeersFromConfig", { enumerable: true, get: function () { return directory_config_js_1.listSlackDirectoryPeersFromConfig; } });
Object.defineProperty(exports, "listTelegramDirectoryGroupsFromConfig", { enumerable: true, get: function () { return directory_config_js_1.listTelegramDirectoryGroupsFromConfig; } });
Object.defineProperty(exports, "listTelegramDirectoryPeersFromConfig", { enumerable: true, get: function () { return directory_config_js_1.listTelegramDirectoryPeersFromConfig; } });
Object.defineProperty(exports, "listWhatsAppDirectoryGroupsFromConfig", { enumerable: true, get: function () { return directory_config_js_1.listWhatsAppDirectoryGroupsFromConfig; } });
Object.defineProperty(exports, "listWhatsAppDirectoryPeersFromConfig", { enumerable: true, get: function () { return directory_config_js_1.listWhatsAppDirectoryPeersFromConfig; } });
var allowlist_match_js_1 = require("../channels/plugins/allowlist-match.js");
Object.defineProperty(exports, "formatAllowlistMatchMeta", { enumerable: true, get: function () { return allowlist_match_js_1.formatAllowlistMatchMeta; } });
var typebox_js_1 = require("../agents/schema/typebox.js");
Object.defineProperty(exports, "optionalStringEnum", { enumerable: true, get: function () { return typebox_js_1.optionalStringEnum; } });
Object.defineProperty(exports, "stringEnum", { enumerable: true, get: function () { return typebox_js_1.stringEnum; } });
var config_schema_js_2 = require("../channels/plugins/config-schema.js");
Object.defineProperty(exports, "buildChannelConfigSchema", { enumerable: true, get: function () { return config_schema_js_2.buildChannelConfigSchema; } });
var config_helpers_js_1 = require("../channels/plugins/config-helpers.js");
Object.defineProperty(exports, "deleteAccountFromConfigSection", { enumerable: true, get: function () { return config_helpers_js_1.deleteAccountFromConfigSection; } });
Object.defineProperty(exports, "setAccountEnabledInConfigSection", { enumerable: true, get: function () { return config_helpers_js_1.setAccountEnabledInConfigSection; } });
var setup_helpers_js_1 = require("../channels/plugins/setup-helpers.js");
Object.defineProperty(exports, "applyAccountNameToChannelSection", { enumerable: true, get: function () { return setup_helpers_js_1.applyAccountNameToChannelSection; } });
Object.defineProperty(exports, "migrateBaseNameToDefaultAccount", { enumerable: true, get: function () { return setup_helpers_js_1.migrateBaseNameToDefaultAccount; } });
var helpers_js_1 = require("../channels/plugins/helpers.js");
Object.defineProperty(exports, "formatPairingApproveHint", { enumerable: true, get: function () { return helpers_js_1.formatPairingApproveHint; } });
var pairing_message_js_1 = require("../channels/plugins/pairing-message.js");
Object.defineProperty(exports, "PAIRING_APPROVED_MESSAGE", { enumerable: true, get: function () { return pairing_message_js_1.PAIRING_APPROVED_MESSAGE; } });
var helpers_js_2 = require("../channels/plugins/onboarding/helpers.js");
Object.defineProperty(exports, "addWildcardAllowFrom", { enumerable: true, get: function () { return helpers_js_2.addWildcardAllowFrom; } });
Object.defineProperty(exports, "promptAccountId", { enumerable: true, get: function () { return helpers_js_2.promptAccountId; } });
var channel_access_js_1 = require("../channels/plugins/onboarding/channel-access.js");
Object.defineProperty(exports, "promptChannelAccessConfig", { enumerable: true, get: function () { return channel_access_js_1.promptChannelAccessConfig; } });
var common_js_1 = require("../agents/tools/common.js");
Object.defineProperty(exports, "createActionGate", { enumerable: true, get: function () { return common_js_1.createActionGate; } });
Object.defineProperty(exports, "jsonResult", { enumerable: true, get: function () { return common_js_1.jsonResult; } });
Object.defineProperty(exports, "readNumberParam", { enumerable: true, get: function () { return common_js_1.readNumberParam; } });
Object.defineProperty(exports, "readReactionParams", { enumerable: true, get: function () { return common_js_1.readReactionParams; } });
Object.defineProperty(exports, "readStringParam", { enumerable: true, get: function () { return common_js_1.readStringParam; } });
var links_js_1 = require("../terminal/links.js");
Object.defineProperty(exports, "formatDocsLink", { enumerable: true, get: function () { return links_js_1.formatDocsLink; } });
var utils_js_1 = require("../utils.js");
Object.defineProperty(exports, "normalizeE164", { enumerable: true, get: function () { return utils_js_1.normalizeE164; } });
var target_errors_js_1 = require("../infra/outbound/target-errors.js");
Object.defineProperty(exports, "missingTargetError", { enumerable: true, get: function () { return target_errors_js_1.missingTargetError; } });
var logger_js_1 = require("../logging/logger.js");
Object.defineProperty(exports, "registerLogTransport", { enumerable: true, get: function () { return logger_js_1.registerLogTransport; } });
var diagnostic_events_js_1 = require("../infra/diagnostic-events.js");
Object.defineProperty(exports, "emitDiagnosticEvent", { enumerable: true, get: function () { return diagnostic_events_js_1.emitDiagnosticEvent; } });
Object.defineProperty(exports, "isDiagnosticsEnabled", { enumerable: true, get: function () { return diagnostic_events_js_1.isDiagnosticsEnabled; } });
Object.defineProperty(exports, "onDiagnosticEvent", { enumerable: true, get: function () { return diagnostic_events_js_1.onDiagnosticEvent; } });
var mime_js_1 = require("../media/mime.js");
Object.defineProperty(exports, "detectMime", { enumerable: true, get: function () { return mime_js_1.detectMime; } });
Object.defineProperty(exports, "extensionForMime", { enumerable: true, get: function () { return mime_js_1.extensionForMime; } });
Object.defineProperty(exports, "getFileExtension", { enumerable: true, get: function () { return mime_js_1.getFileExtension; } });
var store_js_1 = require("../media/store.js");
Object.defineProperty(exports, "extractOriginalFilename", { enumerable: true, get: function () { return store_js_1.extractOriginalFilename; } });
// Channel: Discord
var accounts_js_1 = require("../discord/accounts.js");
Object.defineProperty(exports, "listDiscordAccountIds", { enumerable: true, get: function () { return accounts_js_1.listDiscordAccountIds; } });
Object.defineProperty(exports, "resolveDefaultDiscordAccountId", { enumerable: true, get: function () { return accounts_js_1.resolveDefaultDiscordAccountId; } });
Object.defineProperty(exports, "resolveDiscordAccount", { enumerable: true, get: function () { return accounts_js_1.resolveDiscordAccount; } });
var audit_js_1 = require("../discord/audit.js");
Object.defineProperty(exports, "collectDiscordAuditChannelIds", { enumerable: true, get: function () { return audit_js_1.collectDiscordAuditChannelIds; } });
var discord_js_1 = require("../channels/plugins/onboarding/discord.js");
Object.defineProperty(exports, "discordOnboardingAdapter", { enumerable: true, get: function () { return discord_js_1.discordOnboardingAdapter; } });
var discord_js_2 = require("../channels/plugins/normalize/discord.js");
Object.defineProperty(exports, "looksLikeDiscordTargetId", { enumerable: true, get: function () { return discord_js_2.looksLikeDiscordTargetId; } });
Object.defineProperty(exports, "normalizeDiscordMessagingTarget", { enumerable: true, get: function () { return discord_js_2.normalizeDiscordMessagingTarget; } });
var discord_js_3 = require("../channels/plugins/status-issues/discord.js");
Object.defineProperty(exports, "collectDiscordStatusIssues", { enumerable: true, get: function () { return discord_js_3.collectDiscordStatusIssues; } });
// Channel: iMessage
var accounts_js_2 = require("../imessage/accounts.js");
Object.defineProperty(exports, "listIMessageAccountIds", { enumerable: true, get: function () { return accounts_js_2.listIMessageAccountIds; } });
Object.defineProperty(exports, "resolveDefaultIMessageAccountId", { enumerable: true, get: function () { return accounts_js_2.resolveDefaultIMessageAccountId; } });
Object.defineProperty(exports, "resolveIMessageAccount", { enumerable: true, get: function () { return accounts_js_2.resolveIMessageAccount; } });
var imessage_js_1 = require("../channels/plugins/onboarding/imessage.js");
Object.defineProperty(exports, "imessageOnboardingAdapter", { enumerable: true, get: function () { return imessage_js_1.imessageOnboardingAdapter; } });
var imessage_js_2 = require("../channels/plugins/normalize/imessage.js");
Object.defineProperty(exports, "looksLikeIMessageTargetId", { enumerable: true, get: function () { return imessage_js_2.looksLikeIMessageTargetId; } });
Object.defineProperty(exports, "normalizeIMessageMessagingTarget", { enumerable: true, get: function () { return imessage_js_2.normalizeIMessageMessagingTarget; } });
// Channel: Slack
var accounts_js_3 = require("../slack/accounts.js");
Object.defineProperty(exports, "listEnabledSlackAccounts", { enumerable: true, get: function () { return accounts_js_3.listEnabledSlackAccounts; } });
Object.defineProperty(exports, "listSlackAccountIds", { enumerable: true, get: function () { return accounts_js_3.listSlackAccountIds; } });
Object.defineProperty(exports, "resolveDefaultSlackAccountId", { enumerable: true, get: function () { return accounts_js_3.resolveDefaultSlackAccountId; } });
Object.defineProperty(exports, "resolveSlackAccount", { enumerable: true, get: function () { return accounts_js_3.resolveSlackAccount; } });
Object.defineProperty(exports, "resolveSlackReplyToMode", { enumerable: true, get: function () { return accounts_js_3.resolveSlackReplyToMode; } });
var slack_js_1 = require("../channels/plugins/onboarding/slack.js");
Object.defineProperty(exports, "slackOnboardingAdapter", { enumerable: true, get: function () { return slack_js_1.slackOnboardingAdapter; } });
var slack_js_2 = require("../channels/plugins/normalize/slack.js");
Object.defineProperty(exports, "looksLikeSlackTargetId", { enumerable: true, get: function () { return slack_js_2.looksLikeSlackTargetId; } });
Object.defineProperty(exports, "normalizeSlackMessagingTarget", { enumerable: true, get: function () { return slack_js_2.normalizeSlackMessagingTarget; } });
var threading_tool_context_js_1 = require("../slack/threading-tool-context.js");
Object.defineProperty(exports, "buildSlackThreadingToolContext", { enumerable: true, get: function () { return threading_tool_context_js_1.buildSlackThreadingToolContext; } });
// Channel: Telegram
var accounts_js_4 = require("../telegram/accounts.js");
Object.defineProperty(exports, "listTelegramAccountIds", { enumerable: true, get: function () { return accounts_js_4.listTelegramAccountIds; } });
Object.defineProperty(exports, "resolveDefaultTelegramAccountId", { enumerable: true, get: function () { return accounts_js_4.resolveDefaultTelegramAccountId; } });
Object.defineProperty(exports, "resolveTelegramAccount", { enumerable: true, get: function () { return accounts_js_4.resolveTelegramAccount; } });
var telegram_js_1 = require("../channels/plugins/onboarding/telegram.js");
Object.defineProperty(exports, "telegramOnboardingAdapter", { enumerable: true, get: function () { return telegram_js_1.telegramOnboardingAdapter; } });
var telegram_js_2 = require("../channels/plugins/normalize/telegram.js");
Object.defineProperty(exports, "looksLikeTelegramTargetId", { enumerable: true, get: function () { return telegram_js_2.looksLikeTelegramTargetId; } });
Object.defineProperty(exports, "normalizeTelegramMessagingTarget", { enumerable: true, get: function () { return telegram_js_2.normalizeTelegramMessagingTarget; } });
var telegram_js_3 = require("../channels/plugins/status-issues/telegram.js");
Object.defineProperty(exports, "collectTelegramStatusIssues", { enumerable: true, get: function () { return telegram_js_3.collectTelegramStatusIssues; } });
// Channel: Signal
var accounts_js_5 = require("../signal/accounts.js");
Object.defineProperty(exports, "listSignalAccountIds", { enumerable: true, get: function () { return accounts_js_5.listSignalAccountIds; } });
Object.defineProperty(exports, "resolveDefaultSignalAccountId", { enumerable: true, get: function () { return accounts_js_5.resolveDefaultSignalAccountId; } });
Object.defineProperty(exports, "resolveSignalAccount", { enumerable: true, get: function () { return accounts_js_5.resolveSignalAccount; } });
var signal_js_1 = require("../channels/plugins/onboarding/signal.js");
Object.defineProperty(exports, "signalOnboardingAdapter", { enumerable: true, get: function () { return signal_js_1.signalOnboardingAdapter; } });
var signal_js_2 = require("../channels/plugins/normalize/signal.js");
Object.defineProperty(exports, "looksLikeSignalTargetId", { enumerable: true, get: function () { return signal_js_2.looksLikeSignalTargetId; } });
Object.defineProperty(exports, "normalizeSignalMessagingTarget", { enumerable: true, get: function () { return signal_js_2.normalizeSignalMessagingTarget; } });
// Channel: WhatsApp
var accounts_js_6 = require("../web/accounts.js");
Object.defineProperty(exports, "listWhatsAppAccountIds", { enumerable: true, get: function () { return accounts_js_6.listWhatsAppAccountIds; } });
Object.defineProperty(exports, "resolveDefaultWhatsAppAccountId", { enumerable: true, get: function () { return accounts_js_6.resolveDefaultWhatsAppAccountId; } });
Object.defineProperty(exports, "resolveWhatsAppAccount", { enumerable: true, get: function () { return accounts_js_6.resolveWhatsAppAccount; } });
var normalize_js_1 = require("../whatsapp/normalize.js");
Object.defineProperty(exports, "isWhatsAppGroupJid", { enumerable: true, get: function () { return normalize_js_1.isWhatsAppGroupJid; } });
Object.defineProperty(exports, "normalizeWhatsAppTarget", { enumerable: true, get: function () { return normalize_js_1.normalizeWhatsAppTarget; } });
var whatsapp_js_1 = require("../channels/plugins/onboarding/whatsapp.js");
Object.defineProperty(exports, "whatsappOnboardingAdapter", { enumerable: true, get: function () { return whatsapp_js_1.whatsappOnboardingAdapter; } });
var whatsapp_heartbeat_js_1 = require("../channels/plugins/whatsapp-heartbeat.js");
Object.defineProperty(exports, "resolveWhatsAppHeartbeatRecipients", { enumerable: true, get: function () { return whatsapp_heartbeat_js_1.resolveWhatsAppHeartbeatRecipients; } });
var whatsapp_js_2 = require("../channels/plugins/normalize/whatsapp.js");
Object.defineProperty(exports, "looksLikeWhatsAppTargetId", { enumerable: true, get: function () { return whatsapp_js_2.looksLikeWhatsAppTargetId; } });
Object.defineProperty(exports, "normalizeWhatsAppMessagingTarget", { enumerable: true, get: function () { return whatsapp_js_2.normalizeWhatsAppMessagingTarget; } });
var whatsapp_js_3 = require("../channels/plugins/status-issues/whatsapp.js");
Object.defineProperty(exports, "collectWhatsAppStatusIssues", { enumerable: true, get: function () { return whatsapp_js_3.collectWhatsAppStatusIssues; } });
// Channel: BlueBubbles
var bluebubbles_js_1 = require("../channels/plugins/status-issues/bluebubbles.js");
Object.defineProperty(exports, "collectBlueBubblesStatusIssues", { enumerable: true, get: function () { return bluebubbles_js_1.collectBlueBubblesStatusIssues; } });
// Channel: LINE
var accounts_js_7 = require("../line/accounts.js");
Object.defineProperty(exports, "listLineAccountIds", { enumerable: true, get: function () { return accounts_js_7.listLineAccountIds; } });
Object.defineProperty(exports, "normalizeLineAccountId", { enumerable: true, get: function () { return accounts_js_7.normalizeAccountId; } });
Object.defineProperty(exports, "resolveDefaultLineAccountId", { enumerable: true, get: function () { return accounts_js_7.resolveDefaultLineAccountId; } });
Object.defineProperty(exports, "resolveLineAccount", { enumerable: true, get: function () { return accounts_js_7.resolveLineAccount; } });
var config_schema_js_3 = require("../line/config-schema.js");
Object.defineProperty(exports, "LineConfigSchema", { enumerable: true, get: function () { return config_schema_js_3.LineConfigSchema; } });
var flex_templates_js_1 = require("../line/flex-templates.js");
Object.defineProperty(exports, "createInfoCard", { enumerable: true, get: function () { return flex_templates_js_1.createInfoCard; } });
Object.defineProperty(exports, "createListCard", { enumerable: true, get: function () { return flex_templates_js_1.createListCard; } });
Object.defineProperty(exports, "createImageCard", { enumerable: true, get: function () { return flex_templates_js_1.createImageCard; } });
Object.defineProperty(exports, "createActionCard", { enumerable: true, get: function () { return flex_templates_js_1.createActionCard; } });
Object.defineProperty(exports, "createReceiptCard", { enumerable: true, get: function () { return flex_templates_js_1.createReceiptCard; } });
var markdown_to_line_js_1 = require("../line/markdown-to-line.js");
Object.defineProperty(exports, "processLineMessage", { enumerable: true, get: function () { return markdown_to_line_js_1.processLineMessage; } });
Object.defineProperty(exports, "hasMarkdownToConvert", { enumerable: true, get: function () { return markdown_to_line_js_1.hasMarkdownToConvert; } });
Object.defineProperty(exports, "stripMarkdown", { enumerable: true, get: function () { return markdown_to_line_js_1.stripMarkdown; } });
// Media utilities
var media_js_1 = require("../web/media.js");
Object.defineProperty(exports, "loadWebMedia", { enumerable: true, get: function () { return media_js_1.loadWebMedia; } });
